// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Features.Enrollment
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Agent New Client Enrollment")]
    public partial class AgentNewClientEnrollmentFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AgentNewClientEnrollment.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Agent New Client Enrollment", @"1. Enroll an Agent and verify enrollment
2. Use WebHQ to edit and validate company, set MOU activation date and activate Users
3. Use eVerify to create new clients and verify PENDING status
4. Go back to WebHQ, set MOU date to activate new cliet
5. Go back to eVerify, search for new client and verify status is ACTIVE", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01-Navigate to Agent Registration page")]
        public virtual void _01_NavigateToAgentRegistrationPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01-Navigate to Agent Registration page", ((string[])(null)));
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I navigate to the url for \"registration\" titled \"E-Verify – Employer Registration" +
                    " – Start Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.And("I click on the submit button labeled \"Continue\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Checklist\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02-Employer Registration - Checklist")]
        public virtual void _02_EmployerRegistration_Checklist()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02-Employer Registration - Checklist", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
 testRunner.When("I click on the submit button labeled \"Begin E-Verify Enrollment\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Start Here\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03-Employer Access-N Agent-Y Corporate/Web Services-N")]
        public virtual void _03_EmployerAccess_NAgent_YCorporateWebServices_N()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03-Employer Access-N Agent-Y Corporate/Web Services-N", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
 testRunner.When("I click on the radio button using element id \"radBpNo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.And("I click on the radio button using element id \"radDaYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And("I click on the radio button using element id \"radCorpNo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And("I click on the radio button using element id \"radWsNo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.Then("the page title is \"E-Verify - Employer Registration - Let’s Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04-Registration Review Page Verification")]
        public virtual void _04_RegistrationReviewPageVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04-Registration Review Page Verification", ((string[])(null)));
#line 28
this.ScenarioSetup(scenarioInfo);
#line 29
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 30
 testRunner.When("I access the table using tag \"div\" attribute type \"class\" attribute value \"box\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 31
 testRunner.Then("table row number \"2\" column number \"3\" contains the value \"No\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 32
 testRunner.And("table row number \"3\" column number \"3\" contains the value \"Yes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("table row number \"4\" column number \"3\" contains the value \"No\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.And("table row number \"5\" column number \"3\" contains the value \"No\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05-Registration Review Page")]
        public virtual void _05_RegistrationReviewPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05-Registration Review Page", ((string[])(null)));
#line 36
this.ScenarioSetup(scenarioInfo);
#line 37
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 38
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.Then("the page title is \"E-Verify - Employer Registration - Organization Designation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06-Organization Designation")]
        public virtual void _06_OrganizationDesignation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06-Organization Designation", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 43
 testRunner.When("I select the drop down text \"Federal Government\" using element id \"ucCategory_vsc" +
                    "Category_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 44
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Memorandum of Understanding" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07-Switch to iFrame to verify data")]
        public virtual void _07_SwitchToIFrameToVerifyData()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07-Switch to iFrame to verify data", ((string[])(null)));
#line 47
this.ScenarioSetup(scenarioInfo);
#line 48
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 49
 testRunner.When("I switch to iframe using element id \"ucRegistrationTerms_frmMou\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
 testRunner.Then("the page contains the text \"MEMORANDUM OF UNDERSTANDING\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 51
 testRunner.And("the page contains the text \"FOR E-VERIFY EMPLOYER AGENTS\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
 testRunner.And("I switch back to the body of the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08-Memorandum of Understanding (MOU)")]
        public virtual void _08_MemorandumOfUnderstandingMOU()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08-Memorandum of Understanding (MOU)", ((string[])(null)));
#line 54
this.ScenarioSetup(scenarioInfo);
#line 55
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 56
 testRunner.When("I click on the radio button using element id \"ucRegistrationTerms_radAccept\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.Then("the page title is \"E-Verify – Employer Registration – MOU Signatory\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("09-MOU Signatory")]
        public virtual void _09_MOUSignatory()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09-MOU Signatory", ((string[])(null)));
#line 60
this.ScenarioSetup(scenarioInfo);
#line 61
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 62
 testRunner.When("I set the text box using element id \"ucMouPoc_ltLastName_TextBox\" with the value " +
                    "\"AgentOnly-LN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 63
 testRunner.And("I set the text box using element id \"ucMouPoc_ltFirstName_TextBox\" with the value" +
                    " \"AgentOnly-FN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhoneAreaCode\" with the val" +
                    "ue \"301\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhonePrefixCode\" with the v" +
                    "alue \"123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhoneSuffixCode\" with the v" +
                    "alue \"4567\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
 testRunner.And("I set the text box using element id \"ucMouPoc_ltEmail_TextBox\" with the value \"au" +
                    "tomation.bdd@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
 testRunner.And("I set the text box using element id \"ucMouPoc_ltEmail2_TextBox\" with the value \"a" +
                    "utomation.bdd@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.And("I select the drop down text \"Yes\" using element id \"ucMouPoc_optAccess\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10-Company Information")]
        public virtual void _10_CompanyInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10-Company Information", ((string[])(null)));
#line 73
this.ScenarioSetup(scenarioInfo);
#line 74
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 75
 testRunner.When("I set the text box using element id \"ucCompanyInfo_txtEmpName_TextBox\" with the v" +
                    "alue \"New VariQ Agent\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
 testRunner.And("I set the text box using element id \"ucCompanyInfo_txtAddress1_TextBox\" with the " +
                    "value \"123 Automation Drive\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.And("I set the text box using element id \"ucCompanyInfo_txtCity_TextBox\" with the valu" +
                    "e \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.And("I select the drop down text \"MARYLAND\" using element id \"ucCompanyInfo_vssState_S" +
                    "electorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.And("I set the text box using element id \"ucCompanyInfo_ltzZipCode_TextBox\" with the v" +
                    "alue \"20852\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
 testRunner.And("I select the drop down text \"MONTGOMERY\" using element id \"ucCompanyInfo_vscCount" +
                    "y_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
 testRunner.And("I set the text box using element id \"ucCompanyInfo_ltnEmployerId_TextBox\" with th" +
                    "e value \"123456789\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
 testRunner.And("I select the drop down text \"100 to 499\" using element id \"ucCompanyInfo_vscNbrEm" +
                    "ps_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
 testRunner.Then("the page title is \"E-Verify – Employer Registration – NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11-Generate NAIC Code")]
        public virtual void _11_GenerateNAICCode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11-Generate NAIC Code", ((string[])(null)));
#line 86
this.ScenarioSetup(scenarioInfo);
#line 87
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 88
 testRunner.When("I click on the submit button labeled \"Generate NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
 testRunner.And("I select the drop down text \"FINANCE AND INSURANCE (52)\" using element id \"ucNaic" +
                    "s_scNAICSector_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.And("I click on the submit button labeled \"Continue NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 91
 testRunner.Then("the page title is \"E-Verify – Employer Registration – NAICS Code Subsector\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 92
 testRunner.And("the page contains the text \"FINANCE AND INSURANCE (52)\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("12-NAICS Code - Subsector")]
        public virtual void _12_NAICSCode_Subsector()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12-NAICS Code - Subsector", ((string[])(null)));
#line 94
this.ScenarioSetup(scenarioInfo);
#line 95
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 96
 testRunner.When("I select the drop down text \"MONETARY AUTHORITIES - CENTRAL BANK (521)\" using ele" +
                    "ment id \"ucNaics_scSubsector_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 97
 testRunner.And("I click on the submit button labeled \"Accept NAICS Code and Continue\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Hiring Sites\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("13-Hiring Sites Verification")]
        public virtual void _13_HiringSitesVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13-Hiring Sites Verification", ((string[])(null)));
#line 100
this.ScenarioSetup(scenarioInfo);
#line 101
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 102
 testRunner.Then("the selected drop down text using element id \"ucSites_rptHiringSites__ctl1_lstSta" +
                    "tes\" is \"MARYLAND\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 103
 testRunner.And("the text box using tag \"input\" attribute type \"value\" contains the value \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("14-Navigate to Program Admistrators")]
        public virtual void _14_NavigateToProgramAdmistrators()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14-Navigate to Program Admistrators", ((string[])(null)));
#line 105
this.ScenarioSetup(scenarioInfo);
#line 106
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 107
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 108
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Program Administrators\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("15-Add a Second User")]
        public virtual void _15_AddASecondUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("15-Add a Second User", ((string[])(null)));
#line 110
this.ScenarioSetup(scenarioInfo);
#line 111
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 112
 testRunner.When("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltLastName_T" +
                    "extBox\" with the value \"AO-Second User-LN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 113
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltFirstName_" +
                    "TextBox\" with the value \"AO-Second User-FN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 114
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "eAreaCode\" with the value \"777\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 115
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "ePrefixCode\" with the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 116
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "eSuffixCode\" with the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 117
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltEmail_Text" +
                    "Box\" with the value \"testuser@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltEmail2_Tex" +
                    "tBox\" with the value \"testuser@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 119
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Registration Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("16-Registration Review-Verify Registration Details")]
        [NUnit.Framework.TestCaseAttribute("New VariQ Agent", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123 Automation Drive", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Rockville", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MD", new string[0])]
        [NUnit.Framework.TestCaseAttribute("20852", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MONTGOMERY", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123456789", new string[0])]
        [NUnit.Framework.TestCaseAttribute("100 to 499", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Federal Government", new string[0])]
        [NUnit.Framework.TestCaseAttribute("521 - MONETARY AUTHORITIES - CENTRAL BANK (521)", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MARYLAND", new string[0])]
        [NUnit.Framework.TestCaseAttribute("AO-Second User-LN", new string[0])]
        [NUnit.Framework.TestCaseAttribute("AO-Second User-FN", new string[0])]
        [NUnit.Framework.TestCaseAttribute("(777) 888 - 9999", new string[0])]
        [NUnit.Framework.TestCaseAttribute("automation.bdd@gmail.com", new string[0])]
        public virtual void _16_RegistrationReview_VerifyRegistrationDetails(string textOnPage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("16-Registration Review-Verify Registration Details", exampleTags);
#line 122
this.ScenarioSetup(scenarioInfo);
#line 123
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 124
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("17-Complete Enrollment to Register Agent")]
        public virtual void _17_CompleteEnrollmentToRegisterAgent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("17-Complete Enrollment to Register Agent", ((string[])(null)));
#line 144
this.ScenarioSetup(scenarioInfo);
#line 145
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 146
 testRunner.When("I set the checkbox with element id \"ucSummary_chkAgree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 147
 testRunner.And("I click on the submit button labeled \"Register Employer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 148
 testRunner.Then("the page title is \"E-Verify – Employer Registration – You\'re Finished\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 149
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("18-Logon to WebHQ")]
        public virtual void _18_LogonToWebHQ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("18-Logon to WebHQ", ((string[])(null)));
#line 151
this.ScenarioSetup(scenarioInfo);
#line 152
 testRunner.Given("I navigate to the url for \"webhq\" titled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 153
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 154
 testRunner.And("I click on the button using element id \"btnContinue1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 155
 testRunner.And("I set the text box using element id \"txtUserID\" with the value for \"webhq-usernam" +
                    "e\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 156
 testRunner.And("I set the text box using element id \"txtUserPassword\" with the value for \"webhq-p" +
                    "assword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 157
 testRunner.And("I click on the submit button labeled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 158
 testRunner.Then("the page title is \"Web-HQ: Home\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("19-Search Company")]
        public virtual void _19_SearchCompany()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("19-Search Company", ((string[])(null)));
#line 160
this.ScenarioSetup(scenarioInfo);
#line 161
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 162
 testRunner.When("I click on the link containing the text \"Maintain Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 163
 testRunner.And("the page title is \"Company Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 164
 testRunner.And("I set the text box using element id \"txtEmployer_TextBox\" with the value \"New Var" +
                    "iQ Agent\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 165
 testRunner.And("I click on the submit button labeled \"Display Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 166
 testRunner.Then("the page title is \"Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("20-Navigate to company details")]
        public virtual void _20_NavigateToCompanyDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("20-Navigate to company details", ((string[])(null)));
#line 168
this.ScenarioSetup(scenarioInfo);
#line 169
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 170
 testRunner.When("I access the table using tag \"table\" attribute type \"class\" attribute value \"Cont" +
                    "rolText\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 172
 testRunner.And("I save the table row number containing the data \"PENDING\" in column number \"11\" i" +
                    "nto the variable \"tableRowNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 173
 testRunner.And("I click on the button labeled \"Edit\" in the table row number saved in the variabl" +
                    "e \"tableRowNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 174
 testRunner.Then("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("21-Validate and Match Company")]
        public virtual void _21_ValidateAndMatchCompany()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("21-Validate and Match Company", ((string[])(null)));
#line 176
this.ScenarioSetup(scenarioInfo);
#line 177
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 178
 testRunner.When("I click on the submit button labeled \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 179
 testRunner.And("the page title is \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 180
 testRunner.And("I skip scenario if element is missing using tag \"input\" attribute type \"value\" at" +
                    "tribute value \"Confirm Company Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 181
 testRunner.And("I click on the submit button labeled \"Confirm Company Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 182
 testRunner.And("I select the drop down text \"Match\" using element id \"vscMatchStatus_SelectorDrop" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 183
 testRunner.And("I click on the submit button labeled \"Confirm Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 184
 testRunner.And("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 185
 testRunner.And("I click on the submit button labeled \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 186
 testRunner.And("I access table number \"2\" using tag \"table\" attribute type \"id\" attribute value \"" +
                    "structure\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 187
 testRunner.Then("table row number \"1\" column number \"2\" contains the value \"Match\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("22-Set MOU Signed Date to Activate Users")]
        public virtual void _22_SetMOUSignedDateToActivateUsers()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("22-Set MOU Signed Date to Activate Users", ((string[])(null)));
#line 189
this.ScenarioSetup(scenarioInfo);
#line 190
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 191
 testRunner.When("I click on the submit button labeled \"Return to Maintain Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 192
 testRunner.And("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 193
 testRunner.And("I access table number \"6\" using tag \"table\" attribute type \"id\" attribute value \"" +
                    "structure\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 195
 testRunner.And("I click on the button labeled \"View / Edit\" in row number \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 196
 testRunner.And("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 197
 testRunner.And("I set the text box using element id \"ucCompanyAccess_cdtMOUDate_dateTextBox\" with" +
                    " the value \"01/01/2016\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 198
 testRunner.And("I click on the submit button labeled \"Submit Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 199
 testRunner.And("I access table number \"4\" using tag \"table\" attribute type \"id\" attribute value \"" +
                    "tblAddress\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 200
 testRunner.Then("table row number \"10\" column number \"2\" contains the value \"Total Active Users:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 201
 testRunner.And("table row number \"10\" column number \"3\" contains the value \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("23-Save Active User ID and Edit User")]
        public virtual void _23_SaveActiveUserIDAndEditUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("23-Save Active User ID and Edit User", ((string[])(null)));
#line 203
this.ScenarioSetup(scenarioInfo);
#line 204
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 205
 testRunner.When("I click on the button labeled \"View / Edit\" in row number \"10\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 207
 testRunner.And("the page title is \"Employer User Summary\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 208
 testRunner.And("I access the table using element id \"dgCpsUsers\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 209
 testRunner.And("I save the data from table row number \"3\" column number \"2\" into the variable \"us" +
                    "erid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 210
 testRunner.And("I click on table row number \"3\" in column number \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 212
 testRunner.Then("the page title is \"User Details - View / Modify User Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("24-Set Tutorial Complete and Set Temp Password")]
        public virtual void _24_SetTutorialCompleteAndSetTempPassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("24-Set Tutorial Complete and Set Temp Password", ((string[])(null)));
#line 214
this.ScenarioSetup(scenarioInfo);
#line 215
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 216
 testRunner.When("I set the checkbox with element id \"ucCpsUserModEmployer_chkTutorialComplete\" to " +
                    "\"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 217
 testRunner.And("I set the text box using element id \"ucCpsUserModEmployer_ltbNewPwd_TextBox\" with" +
                    " the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 218
 testRunner.And("I set the text box using element id \"ucCpsUserModEmployer_ltbConfPwd_TextBox\" wit" +
                    "h the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 219
 testRunner.And("I click on the submit button labeled \"Submit User Modifications\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 220
 testRunner.Then("the page title is \"User Confirmation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("25-Logon to eVerify for creating new clients")]
        public virtual void _25_LogonToEVerifyForCreatingNewClients()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("25-Logon to eVerify for creating new clients", ((string[])(null)));
#line 222
this.ScenarioSetup(scenarioInfo);
#line 223
 testRunner.Given("I navigate to the url for \"everify\" titled \"E-Verify: Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 224
 testRunner.When("I click on the submit button containing the text \"I agree\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 225
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_UserIdTextBox_TextBox" +
                    "\" with the value stored in the variable \"userid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 226
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_PasswordTextBox_TextB" +
                    "ox\" with the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 227
 testRunner.And("I click on the submit button labeled \"Log In\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 228
 testRunner.Then("the page title is \"E-Verify: Change Password\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("26-Submit New Password and Security Questions")]
        public virtual void _26_SubmitNewPasswordAndSecurityQuestions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("26-Submit New Password and Security Questions", ((string[])(null)));
#line 230
this.ScenarioSetup(scenarioInfo);
#line 231
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 232
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_ltbOldPwd_TextBox\" wi" +
                    "th the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 233
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ltbNewPwd_TextBox\" wi" +
                    "th the value \"Autotest123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 234
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ltbValidatePwd_TextBo" +
                    "x\" with the value \"Autotest123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 235
 testRunner.And("I select the drop down text \"What is the name of the first school you attended?\" " +
                    "using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 236
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer1_TextBox\" with the value \"abcde\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 237
 testRunner.And("I select the drop down text \"What is the name of your first pet?\" using element i" +
                    "d \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 238
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer2_TextBox\" with the value \"fghij\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 239
 testRunner.And("I select the drop down text \"What is your father\'s middle name?\" using element id" +
                    " \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 240
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer3_TextBox\" with the value \"klmno\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 241
 testRunner.And("I click on the submit button labeled \"Submit\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 242
 testRunner.Then("the page title is \"E-Verify: Update User Profile\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("27-Verify User Profile and logon to eVerify")]
        public virtual void _27_VerifyUserProfileAndLogonToEVerify()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("27-Verify User Profile and logon to eVerify", ((string[])(null)));
#line 244
this.ScenarioSetup(scenarioInfo);
#line 245
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 246
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhoneAreaCode\" contains the value \"301\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 247
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhonePrefixCode\" contains the value \"123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 248
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhoneSuffixCode\" contains the value \"4567\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 249
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_lteUs" +
                    "erEmail_TextBox\" contains the value \"automation.bdd@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 250
 testRunner.When("I click on the submit button labeled \"Submit User Profile Changes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 251
 testRunner.Then("the page title is \"E-Verify: Home Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("28-Navigate to Clients > Add New Client")]
        public virtual void _28_NavigateToClientsAddNewClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("28-Navigate to Clients > Add New Client", ((string[])(null)));
#line 253
this.ScenarioSetup(scenarioInfo);
#line 254
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 255
 testRunner.When("I click on the link using element id \"anch_7\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 256
 testRunner.And("I click on the link using element id \"anch_8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 257
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Organization Designation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("29-Organization Designation")]
        public virtual void _29_OrganizationDesignation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("29-Organization Designation", ((string[])(null)));
#line 259
this.ScenarioSetup(scenarioInfo);
#line 260
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 261
 testRunner.When("I select the drop down text \"Federal Government\" using element id \"MainContentPla" +
                    "ceHolder_ClientCategory1_ddlCategory\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 262
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 263
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("30-Input Client Information")]
        public virtual void _30_InputClientInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("30-Input Client Information", ((string[])(null)));
#line 265
this.ScenarioSetup(scenarioInfo);
#line 266
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 267
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_t" +
                    "xtEmpName_TextBox\" with the value \"New VariQ Client\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 268
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_t" +
                    "xtAddress1_TextBox\" with the value \"123 Test Dr\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 269
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_t" +
                    "xtCity_TextBox\" with the value \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 270
 testRunner.And("I select the drop down text \"MARYLAND\" using element id \"MainContentPlaceHolder_C" +
                    "ompanyInformation1_ddlState\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 271
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_l" +
                    "tzZipCode_TextBox\" with the value \"00000\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 272
 testRunner.And("I select the drop down text \"MONTGOMERY\" using element id \"MainContentPlaceHolder" +
                    "_CompanyInformation1_ddlCounty\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 273
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_l" +
                    "tnEmployerId_TextBox\" with the value \"123456789\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 274
 testRunner.And("I select the drop down text \"2,500 to 4,999\" using element id \"MainContentPlaceHo" +
                    "lder_CompanyInformation1_ddlTotalEmployeeRange\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 275
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 276
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Enter NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("31-NAIC Code for New Client")]
        public virtual void _31_NAICCodeForNewClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("31-NAIC Code for New Client", ((string[])(null)));
#line 278
this.ScenarioSetup(scenarioInfo);
#line 279
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 280
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_Naics_ltNaicsCode_Tex" +
                    "tBox\" with the value \"721\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 281
 testRunner.And("I click on the submit button labeled \"Accept NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 282
 testRunner.Then("the page title is \"E-Verify: Client Wizard - How Many Hiring Sites?\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("32-Hiring Sites")]
        public virtual void _32_HiringSites()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("32-Hiring Sites", ((string[])(null)));
#line 284
this.ScenarioSetup(scenarioInfo);
#line 285
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 286
 testRunner.When("I click on the submit button labeled \"Single Site Verification\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 287
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Enter Program Administrator\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("33-Enter Program Administrator information")]
        public virtual void _33_EnterProgramAdministratorInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("33-Enter Program Administrator information", ((string[])(null)));
#line 289
this.ScenarioSetup(scenarioInfo);
#line 290
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 291
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ltaLastNam" +
                    "e_TextBox\" with the value \"RWD Client-LN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 292
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ltaFirstNa" +
                    "me_TextBox\" with the value \"RWD Client-FN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 293
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ptbPhoneNu" +
                    "mber_PhoneAreaCode\" with the value \"301\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 294
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ptbPhoneNu" +
                    "mber_PhonePrefixCode\" with the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 295
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ptbPhoneNu" +
                    "mber_PhoneSuffixCode\" with the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 296
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_lteEmailAd" +
                    "dress_TextBox\" with the value \"clientemail@variq.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 297
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 298
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Points of Contact Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("34-POC Summary")]
        public virtual void _34_POCSummary()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("34-POC Summary", ((string[])(null)));
#line 300
this.ScenarioSetup(scenarioInfo);
#line 301
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 302
 testRunner.When("I access the table using element id \"MainContentPlaceHolder_ucContacts_ContactsGr" +
                    "id\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 303
 testRunner.Then("table row number \"3\" column number \"1\" contains the value \"RWD Client-LN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 304
 testRunner.And("table row number \"3\" column number \"2\" contains the value \"RWD Client-FN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 305
 testRunner.And("table row number \"3\" column number \"4\" contains the value \"(301) 888 - 9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 306
 testRunner.And("table row number \"3\" column number \"6\" contains the value \"clientemail@variq.com\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("35-Navigate to Company Information")]
        public virtual void _35_NavigateToCompanyInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("35-Navigate to Company Information", ((string[])(null)));
#line 308
this.ScenarioSetup(scenarioInfo);
#line 309
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 310
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 311
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("36-Verify Company Information")]
        [NUnit.Framework.TestCaseAttribute("New VariQ Client", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123 Test Dr", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Rockville", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MD", new string[0])]
        [NUnit.Framework.TestCaseAttribute("00000", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MONTGOMERY", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123456789", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2,500 to 4,999", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Federal Government", new string[0])]
        [NUnit.Framework.TestCaseAttribute("721 - ACCOMMODATION (721)", new string[0])]
        public virtual void _36_VerifyCompanyInformation(string textOnPage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("36-Verify Company Information", exampleTags);
#line 313
this.ScenarioSetup(scenarioInfo);
#line 314
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 315
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("37-Register Client")]
        public virtual void _37_RegisterClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("37-Register Client", ((string[])(null)));
#line 330
this.ScenarioSetup(scenarioInfo);
#line 331
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 332
 testRunner.When("I click on the submit button labeled \"Register Client\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 333
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Thank you for registering for E-Veri" +
                    "fy\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("38: Navigate to Newly Registered Client")]
        public virtual void _38NavigateToNewlyRegisteredClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("38: Navigate to Newly Registered Client", ((string[])(null)));
#line 335
this.ScenarioSetup(scenarioInfo);
#line 336
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 337
 testRunner.When("I click on the link using element id \"anch_7\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 338
 testRunner.And("I click on the link using element id \"anch_9\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 339
 testRunner.And("I click on the submit button labeled \"Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 340
 testRunner.Then("the page title is \"E-Verify: Search Results\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("39: Verify newly created RWD Client")]
        [NUnit.Framework.TestCaseAttribute("3", "New VariQ Client", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "123 Test Dr", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "Rockville", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "MD", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "PENDING", new string[0])]
        public virtual void _39VerifyNewlyCreatedRWDClient(string tableRowNumber, string data, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("39: Verify newly created RWD Client", exampleTags);
#line 342
this.ScenarioSetup(scenarioInfo);
#line 343
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 344
 testRunner.When("I access the table using element id \"MainContentPlaceHolder_ClientCompanyGrid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 345
 testRunner.Then(string.Format("table row number {0} contains the values {1} from the following table", tableRowNumber, data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("40-Logon to WebHQ and search for new client")]
        public virtual void _40_LogonToWebHQAndSearchForNewClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40-Logon to WebHQ and search for new client", ((string[])(null)));
#line 355
this.ScenarioSetup(scenarioInfo);
#line 356
 testRunner.Given("I navigate to the url for \"webhq\" titled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 357
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 358
 testRunner.And("I click on the button using element id \"btnContinue1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 359
 testRunner.And("I set the text box using element id \"txtUserID\" with the value for \"webhq-usernam" +
                    "e\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 360
 testRunner.And("I set the text box using element id \"txtUserPassword\" with the value for \"webhq-p" +
                    "assword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 361
 testRunner.And("I click on the submit button labeled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 362
 testRunner.And("the page title is \"Web-HQ: Home\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 363
 testRunner.And("I click on the link containing the text \"Maintain Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 364
 testRunner.And("the page title is \"Company Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 365
 testRunner.And("I set the text box using element id \"txtEmployer_TextBox\" with the value \"New Var" +
                    "iQ Client\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 366
 testRunner.And("I click on the submit button labeled \"Display Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 367
 testRunner.Then("the page title is \"Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("41-Set Mou date for new client")]
        public virtual void _41_SetMouDateForNewClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41-Set Mou date for new client", ((string[])(null)));
#line 369
this.ScenarioSetup(scenarioInfo);
#line 370
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 371
 testRunner.When("I access the table using tag \"table\" attribute type \"class\" attribute value \"Cont" +
                    "rolText\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 372
 testRunner.And("I save the table row number containing the data \"PENDING\" in column number \"11\" i" +
                    "nto the variable \"tableRowNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 373
 testRunner.And("I click on the button labeled \"Edit\" in the table row number saved in the variabl" +
                    "e \"tableRowNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 374
 testRunner.And("the page title is \"Client Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 375
 testRunner.And("I access table number \"5\" using tag \"table\" attribute type \"id\" attribute value \"" +
                    "tblAddress\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 376
 testRunner.And("I click on the button labeled \"View / Edit\" in row number \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 377
 testRunner.And("I set the text box using element id \"ucCompanyAccess_cdtMOUDate_dateTextBox\" with" +
                    " the value \"01/01/2016\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 378
 testRunner.And("I click on the submit button labeled \"Submit Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 379
 testRunner.Then("table row number \"2\" column number \"3\" contains the value \"01/01/2016\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("42-Finally logon to eVerify and validate new client activation")]
        public virtual void _42_FinallyLogonToEVerifyAndValidateNewClientActivation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("42-Finally logon to eVerify and validate new client activation", ((string[])(null)));
#line 381
this.ScenarioSetup(scenarioInfo);
#line 382
 testRunner.Given("I navigate to the url for \"everify\" titled \"E-Verify: Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 383
 testRunner.When("I click on the submit button containing the text \"I agree\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 384
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_UserIdTextBox_TextBox" +
                    "\" with the value stored in the variable \"userid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 385
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_PasswordTextBox_TextB" +
                    "ox\" with the value \"Autotest123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 386
 testRunner.And("I click on the submit button labeled \"Log In\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 387
 testRunner.And("I click on the link using element id \"anch_7\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 388
 testRunner.And("I click on the link using element id \"anch_9\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 389
 testRunner.And("I click on the submit button labeled \"Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 390
 testRunner.And("I access the table using element id \"MainContentPlaceHolder_ClientCompanyGrid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 391
 testRunner.Then("table row number \"3\" column number \"6\" contains the value \"ACTIVE\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 392
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("50-Set Mou Date-Upload Mou Doc-Activate Client")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _50_SetMouDate_UploadMouDoc_ActivateClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("50-Set Mou Date-Upload Mou Doc-Activate Client", new string[] {
                        "ignore"});
#line 395
this.ScenarioSetup(scenarioInfo);
#line 396
 testRunner.Given("the page title is \"E-Verify: Search Results\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 397
 testRunner.When("I click on the submit button labeled \"Edit\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 398
 testRunner.And("the page title is \"E-Verify: Client Wizard - Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 399
 testRunner.And("I click on the submit button labeled \"Upload Signature Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 400
 testRunner.And("the page title is \"E-Verify: Client Wizard - Upload Client Company Signature Page" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 401
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_UploadMouSignature1_d" +
                    "tMouSigned_dateTextBox\" with the value \"06/06/2016\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 402
 testRunner.And("I upload file \"UploadFiles\\Client_MOU_Signature.gif\" using element id \"MainConten" +
                    "tPlaceHolder_UploadMouSignature1_fileUpload\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 403
 testRunner.And("I click on the submit button labeled \"Submit Electronic Document\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
