// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Features.Enrollment
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Agent New Client WebServices Enrollment")]
    public partial class AgentNewClientWebServicesEnrollmentFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AgentNewClientWebServicesEnrollment.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Agent New Client WebServices Enrollment", @"		1.  Web Services for E-Verify Employer Agent and New Client Enrollment - Register Web Service Employer Agent, Add an Agent Program Administrator, Add a New Client and validate all
		2.  Employer Registration Page & Review (Scenarios 01-06) 
		3.  Organization Designation, MOU Signatory, Company Informations, Agent Program Administrator Informations, Registration Review & Enroll (Scenarios 07-17)
		4.  Use WebHQ - search for agent to edit and validate company, set MOU activation date, save Program Administrator ID, Set Tutorial Complete/Temp Password for Program Admin (Scenarios 34-43)
		5.  Login to everify as an Agent Program Administrator (Scenario 44)
		6.  Validate the Program Administrator - New Password and Security Questions, Verify User Profile (Scenarios 45,46)
		7.  Add a New Client, Organization Designation, Client Informations, Point of Contact(POC), Review & Register  (Scenario 47-56)
		8.  Verify newly added client (Scenario 57-58)
		9.  Use WebHQ - search for client to edit and validate Client - Set Mou date for new client (Scenarios 59-60)
		10. Login to eVerify as an Agent Program Administrator and validate new client activation (Scenario 61-62) ", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01-Navigate to Agent Registration page")]
        public virtual void _01_NavigateToAgentRegistrationPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01-Navigate to Agent Registration page", ((string[])(null)));
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.Given("I navigate to the url for \"registration\" titled \"E-Verify – Employer Registration" +
                    " – Start Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 15
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.And("I click on the submit button labeled \"Continue\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Checklist\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02-Employer Registration - Checklist")]
        public virtual void _02_EmployerRegistration_Checklist()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02-Employer Registration - Checklist", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Checklist\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
 testRunner.When("I click on the submit button labeled \"Begin E-Verify Enrollment\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Start Here\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03-Employer Access-N Agent-Y Corporate-N Web Services-Y")]
        public virtual void _03_EmployerAccess_NAgent_YCorporate_NWebServices_Y()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03-Employer Access-N Agent-Y Corporate-N Web Services-Y", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line 26
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Start Here\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 27
 testRunner.When("I click on the radio button using element id \"radBpNo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
 testRunner.And("I click on the radio button using element id \"radDaYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("I click on the radio button using element id \"radCorpNo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("I click on the radio button using element id \"radWsYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.Then("the page title is \"E-Verify - Employer Registration - Let’s Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04-Registration Review Page Verification")]
        public virtual void _04_RegistrationReviewPageVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04-Registration Review Page Verification", ((string[])(null)));
#line 34
this.ScenarioSetup(scenarioInfo);
#line 35
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 36
 testRunner.When("I access the table using tag \"div\" attribute type \"class\" attribute value \"box\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05 - Registration Review Table Verification")]
        [NUnit.Framework.TestCaseAttribute("2", "No", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "Yes", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4", "No", new string[0])]
        [NUnit.Framework.TestCaseAttribute("5", "Yes", new string[0])]
        public virtual void _05_RegistrationReviewTableVerification(string row, string answer, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 - Registration Review Table Verification", exampleTags);
#line 38
this.ScenarioSetup(scenarioInfo);
#line 39
 testRunner.Then(string.Format("table row number {0} contains the values {1} from the following table", row, answer), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06-Registration Review Page")]
        public virtual void _06_RegistrationReviewPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06-Registration Review Page", ((string[])(null)));
#line 48
this.ScenarioSetup(scenarioInfo);
#line 49
 testRunner.Given("the page title is \"E-Verify - Employer Registration - Let’s Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 50
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 51
 testRunner.Then("the page title is \"E-Verify - Employer Registration - Organization Designation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07-Organization Designation")]
        public virtual void _07_OrganizationDesignation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07-Organization Designation", ((string[])(null)));
#line 53
this.ScenarioSetup(scenarioInfo);
#line 54
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 55
 testRunner.When("I select the drop down text \"Federal Government\" using element id \"ucCategory_vsc" +
                    "Category_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Memorandum of Understanding" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08-Switch to iFrame to verify data")]
        public virtual void _08_SwitchToIFrameToVerifyData()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08-Switch to iFrame to verify data", ((string[])(null)));
#line 59
this.ScenarioSetup(scenarioInfo);
#line 60
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 61
 testRunner.When("I switch to iframe using element id \"ucRegistrationTerms_frmMou\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
 testRunner.Then("the page contains the text \"MEMORANDUM OF UNDERSTANDING\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 63
 testRunner.And("the page contains the text \"FOR WEB SERVICES E-VERIFY EMPLOYER AGENTS\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.And("I switch back to the body of the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("09-Memorandum of Understanding (MOU)")]
        public virtual void _09_MemorandumOfUnderstandingMOU()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09-Memorandum of Understanding (MOU)", ((string[])(null)));
#line 66
this.ScenarioSetup(scenarioInfo);
#line 67
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Memorandum of Understanding" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 68
 testRunner.When("I click on the radio button using element id \"ucRegistrationTerms_radAccept\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 69
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
 testRunner.Then("the page title is \"E-Verify – Employer Registration – MOU Signatory\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10-MOU Signatory")]
        public virtual void _10_MOUSignatory()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10-MOU Signatory", ((string[])(null)));
#line 72
this.ScenarioSetup(scenarioInfo);
#line 73
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 74
 testRunner.When("I set the text box using element id \"ucMouPoc_ltLastName_TextBox\" with the value " +
                    "\"AgentWebServiceOnly-LN-one\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 75
 testRunner.And("I set the text box using element id \"ucMouPoc_ltFirstName_TextBox\" with the value" +
                    " \"AgentWebServiceOnly-FN-one\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhoneAreaCode\" with the val" +
                    "ue \"301\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhonePrefixCode\" with the v" +
                    "alue \"123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhoneSuffixCode\" with the v" +
                    "alue \"4567\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.And("I set the text box using element id \"ucMouPoc_ltEmail_TextBox\" with the value \"au" +
                    "tomation.bdd@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
 testRunner.And("I set the text box using element id \"ucMouPoc_ltEmail2_TextBox\" with the value \"a" +
                    "utomation.bdd@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
 testRunner.And("I select the drop down text \"No\" using element id \"ucMouPoc_optAccess\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11-Company Information")]
        public virtual void _11_CompanyInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11-Company Information", ((string[])(null)));
#line 85
this.ScenarioSetup(scenarioInfo);
#line 86
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 87
 testRunner.When("I set the text box using element id \"ucCompanyInfo_txtEmpName_TextBox\" with the v" +
                    "alue \"Variq Web Service Agent\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 88
 testRunner.And("I set the text box using element id \"ucCompanyInfo_txtAddress1_TextBox\" with the " +
                    "value \"123 Automation Drive\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 89
 testRunner.And("I set the text box using element id \"ucCompanyInfo_txtCity_TextBox\" with the valu" +
                    "e \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.And("I select the drop down text \"MARYLAND\" using element id \"ucCompanyInfo_vssState_S" +
                    "electorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 91
 testRunner.And("I set the text box using element id \"ucCompanyInfo_ltzZipCode_TextBox\" with the v" +
                    "alue \"20852\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 92
 testRunner.And("I select the drop down text \"MONTGOMERY\" using element id \"ucCompanyInfo_vscCount" +
                    "y_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 93
 testRunner.And("I set the text box using element id \"ucCompanyInfo_ltnEmployerId_TextBox\" with th" +
                    "e value \"123456789\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 94
 testRunner.And("I select the drop down text \"100 to 499\" using element id \"ucCompanyInfo_vscNbrEm" +
                    "ps_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 95
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 96
 testRunner.Then("the page title is \"E-Verify – Employer Registration – NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("12 - NAICS Code for new Web Service Agent")]
        public virtual void _12_NAICSCodeForNewWebServiceAgent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12 - NAICS Code for new Web Service Agent", ((string[])(null)));
#line 98
this.ScenarioSetup(scenarioInfo);
#line 99
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 100
 testRunner.When("I set the text box using element id \"ucNaics_ltNaicsCode_TextBox\" with the value " +
                    "\"521\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 101
 testRunner.And("I click on the submit button labeled \"Accept NAICS Code and Continue\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 102
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Hiring Sites\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("13-Hiring Sites Verification")]
        public virtual void _13_HiringSitesVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13-Hiring Sites Verification", ((string[])(null)));
#line 104
this.ScenarioSetup(scenarioInfo);
#line 105
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 106
 testRunner.Then("the selected drop down text using element id \"ucSites_rptHiringSites__ctl1_lstSta" +
                    "tes\" is \"MARYLAND\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 107
 testRunner.And("the text box using tag \"input\" attribute type \"value\" contains the value \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("14-Navigate to Program Admistrators")]
        public virtual void _14_NavigateToProgramAdmistrators()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14-Navigate to Program Admistrators", ((string[])(null)));
#line 109
this.ScenarioSetup(scenarioInfo);
#line 110
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Hiring Sites\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 111
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 112
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Program Administrators\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("15-Add a Web Service Agent Program Administrator")]
        public virtual void _15_AddAWebServiceAgentProgramAdministrator()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("15-Add a Web Service Agent Program Administrator", ((string[])(null)));
#line 114
this.ScenarioSetup(scenarioInfo);
#line 115
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 116
 testRunner.When("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltLastName_T" +
                    "extBox\" with the value \"AO-Web Services User-LN-One\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 117
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltFirstName_" +
                    "TextBox\" with the value \"AO-Web Services User-FN-One\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "eAreaCode\" with the value \"777\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 119
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "ePrefixCode\" with the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "eSuffixCode\" with the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 121
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltEmail_Text" +
                    "Box\" with the value \"testuser@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 122
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltEmail2_Tex" +
                    "tBox\" with the value \"testuser@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 124
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Registration Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("16-Registration Review-Verify Registration Details")]
        [NUnit.Framework.TestCaseAttribute("Variq Web Service Agent", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123 Automation Drive", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Rockville", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MD", new string[0])]
        [NUnit.Framework.TestCaseAttribute("20852", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MONTGOMERY", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123456789", new string[0])]
        [NUnit.Framework.TestCaseAttribute("100 to 499", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Federal Government", new string[0])]
        [NUnit.Framework.TestCaseAttribute("521 - MONETARY AUTHORITIES - CENTRAL BANK", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MARYLAND", new string[0])]
        [NUnit.Framework.TestCaseAttribute("AO-Web Services User-LN-One", new string[0])]
        [NUnit.Framework.TestCaseAttribute("AO-Web Services User-FN-O", new string[0])]
        [NUnit.Framework.TestCaseAttribute("(777) 888 - 9999", new string[0])]
        [NUnit.Framework.TestCaseAttribute("testuser@test.com", new string[0])]
        public virtual void _16_RegistrationReview_VerifyRegistrationDetails(string textOnPage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("16-Registration Review-Verify Registration Details", exampleTags);
#line 126
this.ScenarioSetup(scenarioInfo);
#line 127
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 128
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("17-Complete Enrollment to Register Web Service Agent")]
        public virtual void _17_CompleteEnrollmentToRegisterWebServiceAgent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("17-Complete Enrollment to Register Web Service Agent", ((string[])(null)));
#line 148
this.ScenarioSetup(scenarioInfo);
#line 149
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Registration Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 150
 testRunner.When("I set the checkbox with element id \"ucSummary_chkAgree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 151
 testRunner.And("I click on the submit button labeled \"Register Employer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 152
 testRunner.Then("the page title is \"E-Verify – Employer Registration – You\'re Finished\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 153
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("18-Navigate to Agent Registration page")]
        public virtual void _18_NavigateToAgentRegistrationPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("18-Navigate to Agent Registration page", ((string[])(null)));
#line 155
this.ScenarioSetup(scenarioInfo);
#line 156
 testRunner.Given("I navigate to the url for \"registration\" titled \"E-Verify – Employer Registration" +
                    " – Start Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 157
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 158
 testRunner.And("I click on the submit button labeled \"Continue\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Checklist\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("19-Employer Registration - Checklist")]
        public virtual void _19_EmployerRegistration_Checklist()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("19-Employer Registration - Checklist", ((string[])(null)));
#line 161
this.ScenarioSetup(scenarioInfo);
#line 162
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 163
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Checklist\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 164
 testRunner.When("I click on the submit button labeled \"Begin E-Verify Enrollment\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 165
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Start Here\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("20-Employer Access-N Agent-Y Corporate-N Web Services-Y")]
        public virtual void _20_EmployerAccess_NAgent_YCorporate_NWebServices_Y()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("20-Employer Access-N Agent-Y Corporate-N Web Services-Y", ((string[])(null)));
#line 167
this.ScenarioSetup(scenarioInfo);
#line 168
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Start Here\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 169
 testRunner.When("I click on the radio button using element id \"radBpNo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 170
 testRunner.And("I click on the radio button using element id \"radDaYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 171
 testRunner.And("I click on the radio button using element id \"radCorpNo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 172
 testRunner.And("I click on the radio button using element id \"radWsYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 173
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 174
 testRunner.Then("the page title is \"E-Verify - Employer Registration - Let’s Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("21-Registration Review Page Verification")]
        public virtual void _21_RegistrationReviewPageVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("21-Registration Review Page Verification", ((string[])(null)));
#line 176
this.ScenarioSetup(scenarioInfo);
#line 177
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 178
 testRunner.When("I access the table using tag \"div\" attribute type \"class\" attribute value \"box\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("22 - Registration Review Table Verification")]
        [NUnit.Framework.TestCaseAttribute("2", "No", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "Yes", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4", "No", new string[0])]
        [NUnit.Framework.TestCaseAttribute("5", "Yes", new string[0])]
        public virtual void _22_RegistrationReviewTableVerification(string row, string answer, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("22 - Registration Review Table Verification", exampleTags);
#line 180
this.ScenarioSetup(scenarioInfo);
#line 181
 testRunner.Then(string.Format("table row number {0} contains the values {1} from the following table", row, answer), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("23-Registration Review Page")]
        public virtual void _23_RegistrationReviewPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("23-Registration Review Page", ((string[])(null)));
#line 190
this.ScenarioSetup(scenarioInfo);
#line 191
 testRunner.Given("the page title is \"E-Verify - Employer Registration - Let’s Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 192
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 193
 testRunner.Then("the page title is \"E-Verify - Employer Registration - Organization Designation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("24-Organization Designation")]
        public virtual void _24_OrganizationDesignation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("24-Organization Designation", ((string[])(null)));
#line 195
this.ScenarioSetup(scenarioInfo);
#line 196
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 197
 testRunner.When("I select the drop down text \"Federal Government\" using element id \"ucCategory_vsc" +
                    "Category_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 198
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 199
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Memorandum of Understanding" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("25-Switch to iFrame to verify data")]
        public virtual void _25_SwitchToIFrameToVerifyData()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("25-Switch to iFrame to verify data", ((string[])(null)));
#line 201
this.ScenarioSetup(scenarioInfo);
#line 202
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 203
 testRunner.When("I switch to iframe using element id \"ucRegistrationTerms_frmMou\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 204
 testRunner.Then("the page contains the text \"MEMORANDUM OF UNDERSTANDING\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 205
 testRunner.And("the page contains the text \"FOR WEB SERVICES E-VERIFY EMPLOYER AGENTS\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 206
 testRunner.And("I switch back to the body of the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("26-Memorandum of Understanding (MOU)")]
        public virtual void _26_MemorandumOfUnderstandingMOU()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("26-Memorandum of Understanding (MOU)", ((string[])(null)));
#line 208
this.ScenarioSetup(scenarioInfo);
#line 209
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Memorandum of Understanding" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 210
 testRunner.When("I click on the radio button using element id \"ucRegistrationTerms_radAccept\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 211
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 212
 testRunner.Then("the page title is \"E-Verify – Employer Registration – MOU Signatory\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("27-MOU Signatory")]
        public virtual void _27_MOUSignatory()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("27-MOU Signatory", ((string[])(null)));
#line 214
this.ScenarioSetup(scenarioInfo);
#line 215
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 216
 testRunner.When("I set the text box using element id \"ucMouPoc_ltLastName_TextBox\" with the value " +
                    "\"AgentWebServiceOnly-LN-one\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 217
 testRunner.And("I set the text box using element id \"ucMouPoc_ltFirstName_TextBox\" with the value" +
                    " \"AgentWebServiceOnly-FN-one\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 218
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhoneAreaCode\" with the val" +
                    "ue \"301\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 219
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhonePrefixCode\" with the v" +
                    "alue \"123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 220
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhoneSuffixCode\" with the v" +
                    "alue \"4567\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 221
 testRunner.And("I set the text box using element id \"ucMouPoc_ltEmail_TextBox\" with the value \"au" +
                    "tomation.bdd@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 222
 testRunner.And("I set the text box using element id \"ucMouPoc_ltEmail2_TextBox\" with the value \"a" +
                    "utomation.bdd@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 223
 testRunner.And("I select the drop down text \"No\" using element id \"ucMouPoc_optAccess\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 224
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 225
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("28-Company Information")]
        public virtual void _28_CompanyInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("28-Company Information", ((string[])(null)));
#line 227
this.ScenarioSetup(scenarioInfo);
#line 228
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 229
 testRunner.When("I set the text box using element id \"ucCompanyInfo_txtEmpName_TextBox\" with the v" +
                    "alue \"Variq Web Service Agent\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 230
 testRunner.And("I set the text box using element id \"ucCompanyInfo_txtAddress1_TextBox\" with the " +
                    "value \"123 Automation Drive\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 231
 testRunner.And("I set the text box using element id \"ucCompanyInfo_txtCity_TextBox\" with the valu" +
                    "e \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 232
 testRunner.And("I select the drop down text \"MARYLAND\" using element id \"ucCompanyInfo_vssState_S" +
                    "electorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 233
 testRunner.And("I set the text box using element id \"ucCompanyInfo_ltzZipCode_TextBox\" with the v" +
                    "alue \"20852\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 234
 testRunner.And("I select the drop down text \"MONTGOMERY\" using element id \"ucCompanyInfo_vscCount" +
                    "y_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 235
 testRunner.And("I set the text box using element id \"ucCompanyInfo_ltnEmployerId_TextBox\" with th" +
                    "e value \"123456789\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 236
 testRunner.And("I select the drop down text \"100 to 499\" using element id \"ucCompanyInfo_vscNbrEm" +
                    "ps_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 237
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 238
 testRunner.Then("the page title is \"E-Verify – Employer Registration – NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("29 - NAICS Code for new Web Service Agent")]
        public virtual void _29_NAICSCodeForNewWebServiceAgent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("29 - NAICS Code for new Web Service Agent", ((string[])(null)));
#line 240
this.ScenarioSetup(scenarioInfo);
#line 241
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 242
 testRunner.When("I set the text box using element id \"ucNaics_ltNaicsCode_TextBox\" with the value " +
                    "\"521\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 243
 testRunner.And("I click on the submit button labeled \"Accept NAICS Code and Continue\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 244
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Hiring Sites\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("30-Hiring Sites Verification")]
        public virtual void _30_HiringSitesVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("30-Hiring Sites Verification", ((string[])(null)));
#line 246
this.ScenarioSetup(scenarioInfo);
#line 247
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 248
 testRunner.Then("the selected drop down text using element id \"ucSites_rptHiringSites__ctl1_lstSta" +
                    "tes\" is \"MARYLAND\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 249
 testRunner.And("the text box using tag \"input\" attribute type \"value\" contains the value \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("31-Navigate to Program Admistrators")]
        public virtual void _31_NavigateToProgramAdmistrators()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("31-Navigate to Program Admistrators", ((string[])(null)));
#line 251
this.ScenarioSetup(scenarioInfo);
#line 252
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Hiring Sites\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 253
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 254
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Program Administrators\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("32-Add a Web Service Agent Program Administrator")]
        public virtual void _32_AddAWebServiceAgentProgramAdministrator()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("32-Add a Web Service Agent Program Administrator", ((string[])(null)));
#line 256
this.ScenarioSetup(scenarioInfo);
#line 257
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 258
 testRunner.When("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltLastName_T" +
                    "extBox\" with the value \"AO-Web Services User-LN-One\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 259
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltFirstName_" +
                    "TextBox\" with the value \"AO-Web Services User-FN-One\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 260
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "eAreaCode\" with the value \"777\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 261
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "ePrefixCode\" with the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 262
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "eSuffixCode\" with the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 263
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltEmail_Text" +
                    "Box\" with the value \"testuser@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 264
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltEmail2_Tex" +
                    "tBox\" with the value \"testuser@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 265
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 266
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Registration Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("33-Registration Review-Verify Registration Details")]
        [NUnit.Framework.TestCaseAttribute("Variq Web Service Agent", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123 Automation Drive", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Rockville", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MD", new string[0])]
        [NUnit.Framework.TestCaseAttribute("20852", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MONTGOMERY", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123456789", new string[0])]
        [NUnit.Framework.TestCaseAttribute("100 to 499", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Federal Government", new string[0])]
        [NUnit.Framework.TestCaseAttribute("521 - MONETARY AUTHORITIES - CENTRAL BANK", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MARYLAND", new string[0])]
        [NUnit.Framework.TestCaseAttribute("AO-Web Services User-LN-One", new string[0])]
        [NUnit.Framework.TestCaseAttribute("AO-Web Services User-FN-O", new string[0])]
        [NUnit.Framework.TestCaseAttribute("(777) 888 - 9999", new string[0])]
        [NUnit.Framework.TestCaseAttribute("testuser@test.com", new string[0])]
        public virtual void _33_RegistrationReview_VerifyRegistrationDetails(string textOnPage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("33-Registration Review-Verify Registration Details", exampleTags);
#line 268
this.ScenarioSetup(scenarioInfo);
#line 269
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 270
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("34-Complete Enrollment to Register Web Service Agent")]
        public virtual void _34_CompleteEnrollmentToRegisterWebServiceAgent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("34-Complete Enrollment to Register Web Service Agent", ((string[])(null)));
#line 290
this.ScenarioSetup(scenarioInfo);
#line 291
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Registration Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 292
 testRunner.When("I set the checkbox with element id \"ucSummary_chkAgree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 293
 testRunner.And("I click on the submit button labeled \"Register Employer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 294
 testRunner.Then("the page title is \"E-Verify – Employer Registration – You\'re Finished\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 295
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("35-Logon to WebHQ")]
        public virtual void _35_LogonToWebHQ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("35-Logon to WebHQ", ((string[])(null)));
#line 297
this.ScenarioSetup(scenarioInfo);
#line 298
 testRunner.Given("I navigate to the url for \"webhq\" titled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 299
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 300
 testRunner.And("I click on the button using element id \"btnContinue1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 301
 testRunner.And("I set the text box using element id \"txtUserID\" with the value for \"webhq-usernam" +
                    "e\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 302
 testRunner.And("I set the text box using element id \"txtUserPassword\" with the value for \"webhq-p" +
                    "assword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 303
 testRunner.And("I click on the submit button labeled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 304
 testRunner.Then("the page title is \"Web-HQ: Home\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("36-Search Company")]
        public virtual void _36_SearchCompany()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("36-Search Company", ((string[])(null)));
#line 306
this.ScenarioSetup(scenarioInfo);
#line 307
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 308
 testRunner.When("I click on the link containing the text \"Maintain Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 309
 testRunner.And("the page title is \"Company Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 310
 testRunner.And("I set the text box using element id \"txtEmployer_TextBox\" with the value \"Variq W" +
                    "eb Service Agent\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 311
 testRunner.And("I click on the submit button labeled \"Display Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 312
 testRunner.Then("the page title is \"Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("37-Navigate to company details")]
        public virtual void _37_NavigateToCompanyDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("37-Navigate to company details", ((string[])(null)));
#line 314
this.ScenarioSetup(scenarioInfo);
#line 315
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 316
 testRunner.When("I access the table using tag \"table\" attribute type \"class\" attribute value \"Cont" +
                    "rolText\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 317
 testRunner.And("I save the table row number containing the data \"PENDING\" in column number \"11\" i" +
                    "nto the variable \"tableRowNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 318
 testRunner.And("I click on the button labeled \"Edit\" in the table row number saved in the variabl" +
                    "e \"tableRowNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 319
 testRunner.Then("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("38-Validate Access Method - Web DABP / WS-EMP")]
        [NUnit.Framework.TestCaseAttribute("WEB-DABP", new string[0])]
        [NUnit.Framework.TestCaseAttribute("WS-EMP", new string[0])]
        public virtual void _38_ValidateAccessMethod_WebDABPWS_EMP(string access, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("38-Validate Access Method - Web DABP / WS-EMP", exampleTags);
#line 321
this.ScenarioSetup(scenarioInfo);
#line 322
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 323
 testRunner.Then(string.Format("the page contains the text {0} from the following table", access), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("39-Validate and Match Company")]
        public virtual void _39_ValidateAndMatchCompany()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("39-Validate and Match Company", ((string[])(null)));
#line 330
this.ScenarioSetup(scenarioInfo);
#line 331
 testRunner.Given("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 332
 testRunner.When("I click on the submit button labeled \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 333
 testRunner.And("the page title is \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 334
 testRunner.And("I skip scenario if element is missing using tag \"input\" attribute type \"value\" at" +
                    "tribute value \"Confirm Company Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 335
 testRunner.And("I click on the submit button labeled \"Confirm Company Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 336
 testRunner.And("I select the drop down text \"Match\" using element id \"vscMatchStatus_SelectorDrop" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 337
 testRunner.And("I click on the submit button labeled \"Confirm Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 338
 testRunner.And("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 339
 testRunner.And("I click on the submit button labeled \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 340
 testRunner.And("I access table number \"2\" using tag \"table\" attribute type \"id\" attribute value \"" +
                    "structure\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 341
 testRunner.Then("table row number \"1\" column number \"2\" contains the value \"Match\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("40-Set MOU Signed Date")]
        public virtual void _40_SetMOUSignedDate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40-Set MOU Signed Date", ((string[])(null)));
#line 343
this.ScenarioSetup(scenarioInfo);
#line 344
 testRunner.Given("the page title is \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 345
 testRunner.When("I click on the submit button labeled \"Return to Maintain Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 346
 testRunner.And("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 347
 testRunner.And("I access table number \"6\" using tag \"table\" attribute type \"id\" attribute value \"" +
                    "structure\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 348
 testRunner.And("I click on the button labeled \"View / Edit\" in row number \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 349
 testRunner.And("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 350
 testRunner.And("I set the text box using element id \"ucCompanyAccess_cdtMOUDate_dateTextBox\" with" +
                    " the value \"06/20/2016\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 351
 testRunner.And("I click on the submit button labeled \"Submit Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 352
 testRunner.And("I access table number \"4\" using tag \"table\" attribute type \"id\" attribute value \"" +
                    "tblAddress\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 353
 testRunner.Then("table row number \"10\" column number \"2\" contains the value \"Total Active Users:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 354
 testRunner.And("table row number \"10\" column number \"3\" contains the value \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("41-Save Active User ID and Edit User")]
        public virtual void _41_SaveActiveUserIDAndEditUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41-Save Active User ID and Edit User", ((string[])(null)));
#line 356
this.ScenarioSetup(scenarioInfo);
#line 357
 testRunner.Given("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 358
 testRunner.When("I click on the button labeled \"View / Edit\" in row number \"10\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 359
 testRunner.And("the page title is \"Employer User Summary\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 360
 testRunner.And("I access the table using element id \"dgCpsUsers\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 361
 testRunner.And("I save the data from table row number \"3\" column number \"2\" into the variable \"us" +
                    "erid1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 362
 testRunner.And("I click on table row number \"3\" in column number \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 363
 testRunner.Then("the page title is \"User Details - View / Modify User Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("42-Set Tutorial Complete/Temp Password for Program Admin")]
        public virtual void _42_SetTutorialCompleteTempPasswordForProgramAdmin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("42-Set Tutorial Complete/Temp Password for Program Admin", ((string[])(null)));
#line 365
this.ScenarioSetup(scenarioInfo);
#line 366
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 367
 testRunner.When("I set the checkbox with element id \"ucCpsUserModEmployer_chkTutorialComplete\" to " +
                    "\"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 368
 testRunner.And("I set the text box using element id \"ucCpsUserModEmployer_ltbNewPwd_TextBox\" with" +
                    " the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 369
 testRunner.And("I set the text box using element id \"ucCpsUserModEmployer_ltbConfPwd_TextBox\" wit" +
                    "h the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 370
 testRunner.And("I click on the submit button labeled \"Submit User Modifications\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 371
 testRunner.Then("the page title is \"User Confirmation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("43-Signout from Web-HQ")]
        public virtual void _43_SignoutFromWeb_HQ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("43-Signout from Web-HQ", ((string[])(null)));
#line 373
this.ScenarioSetup(scenarioInfo);
#line 374
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 375
 testRunner.When("I click on the button using element id \"ucVisNav_hlExit\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 376
 testRunner.Then("the page title is \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 377
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("44-Logon to eVerify for creating new clients")]
        public virtual void _44_LogonToEVerifyForCreatingNewClients()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("44-Logon to eVerify for creating new clients", ((string[])(null)));
#line 379
this.ScenarioSetup(scenarioInfo);
#line 380
 testRunner.Given("I navigate to the url for \"everify\" titled \"E-Verify: Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 381
 testRunner.When("I click on the submit button containing the text \"I agree\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 382
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_UserIdTextBox_TextBox" +
                    "\" with the value stored in the variable \"userid1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 383
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_PasswordTextBox_TextB" +
                    "ox\" with the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 384
 testRunner.And("I click on the submit button labeled \"Log In\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 385
 testRunner.Then("the page title is \"E-Verify: Change Password\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("45-Submit New Password and Security Questions")]
        public virtual void _45_SubmitNewPasswordAndSecurityQuestions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("45-Submit New Password and Security Questions", ((string[])(null)));
#line 387
this.ScenarioSetup(scenarioInfo);
#line 388
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 389
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_ltbOldPwd_TextBox\" wi" +
                    "th the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 390
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ltbNewPwd_TextBox\" wi" +
                    "th the value \"Autotest123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 391
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ltbValidatePwd_TextBo" +
                    "x\" with the value \"Autotest123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 392
 testRunner.And("I select the drop down text \"What is the name of the first school you attended?\" " +
                    "using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 393
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer1_TextBox\" with the value \"abcde\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 394
 testRunner.And("I select the drop down text \"What is the name of your first pet?\" using element i" +
                    "d \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 395
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer2_TextBox\" with the value \"fghij\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 396
 testRunner.And("I select the drop down text \"What is your father\'s middle name?\" using element id" +
                    " \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 397
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer3_TextBox\" with the value \"klmno\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 398
 testRunner.And("I click on the submit button labeled \"Submit\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 399
 testRunner.Then("the page title is \"E-Verify: Update User Profile\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("46-Verify User Profile and logon to eVerify")]
        public virtual void _46_VerifyUserProfileAndLogonToEVerify()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("46-Verify User Profile and logon to eVerify", ((string[])(null)));
#line 401
this.ScenarioSetup(scenarioInfo);
#line 402
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 403
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhoneAreaCode\" contains the value \"777\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 404
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhonePrefixCode\" contains the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 405
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhoneSuffixCode\" contains the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 406
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_lteUs" +
                    "erEmail_TextBox\" contains the value \"testuser@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 407
 testRunner.When("I click on the submit button labeled \"Submit User Profile Changes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 408
 testRunner.Then("the page title is \"E-Verify: Home Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("47-Navigate to Clients > Add New Client")]
        public virtual void _47_NavigateToClientsAddNewClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("47-Navigate to Clients > Add New Client", ((string[])(null)));
#line 410
this.ScenarioSetup(scenarioInfo);
#line 411
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 412
 testRunner.When("I click on the link using element id \"anch_7\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 413
 testRunner.And("I click on the link containing the text \"Add New Client\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 414
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Organization Designation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("48-Organization Designation")]
        public virtual void _48_OrganizationDesignation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("48-Organization Designation", ((string[])(null)));
#line 416
this.ScenarioSetup(scenarioInfo);
#line 417
 testRunner.Given("the page title is \"E-Verify: Client Wizard - Organization Designation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 418
 testRunner.When("I select the drop down text \"Federal Government\" using element id \"MainContentPla" +
                    "ceHolder_ClientCategory1_ddlCategory\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 419
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 420
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("49-Input Client Information")]
        public virtual void _49_InputClientInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("49-Input Client Information", ((string[])(null)));
#line 422
this.ScenarioSetup(scenarioInfo);
#line 423
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 424
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_t" +
                    "xtEmpName_TextBox\" with the value \"VariQ Web Service Agent - Client\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 425
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_t" +
                    "xtAddress1_TextBox\" with the value \"123 Test Dr\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 426
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_t" +
                    "xtCity_TextBox\" with the value \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 427
 testRunner.And("I select the drop down text \"MARYLAND\" using element id \"MainContentPlaceHolder_C" +
                    "ompanyInformation1_ddlState\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 428
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_l" +
                    "tzZipCode_TextBox\" with the value \"00000\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 429
 testRunner.And("I select the drop down text \"MONTGOMERY\" using element id \"MainContentPlaceHolder" +
                    "_CompanyInformation1_ddlCounty\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 430
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_l" +
                    "tnEmployerId_TextBox\" with the value \"123456789\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 431
 testRunner.And("I select the drop down text \"2,500 to 4,999\" using element id \"MainContentPlaceHo" +
                    "lder_CompanyInformation1_ddlTotalEmployeeRange\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 432
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 433
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Enter NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("50-NAIC Code for New Client")]
        public virtual void _50_NAICCodeForNewClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("50-NAIC Code for New Client", ((string[])(null)));
#line 435
this.ScenarioSetup(scenarioInfo);
#line 436
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 437
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_Naics_ltNaicsCode_Tex" +
                    "tBox\" with the value \"721\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 438
 testRunner.And("I click on the submit button labeled \"Accept NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 439
 testRunner.Then("the page title is \"E-Verify: Client Wizard - How Many Hiring Sites?\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("51-Hiring Sites")]
        public virtual void _51_HiringSites()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("51-Hiring Sites", ((string[])(null)));
#line 441
this.ScenarioSetup(scenarioInfo);
#line 442
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 443
 testRunner.When("I click on the submit button labeled \"Single Site Verification\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 444
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Enter Program Administrator\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("52-Enter POC Details")]
        public virtual void _52_EnterPOCDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("52-Enter POC Details", ((string[])(null)));
#line 446
this.ScenarioSetup(scenarioInfo);
#line 447
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 448
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ltaLastNam" +
                    "e_TextBox\" with the value \"Web Service Client-LN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 449
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ltaFirstNa" +
                    "me_TextBox\" with the value \"Web Service Client-FN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 450
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ptbPhoneNu" +
                    "mber_PhoneAreaCode\" with the value \"301\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 451
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ptbPhoneNu" +
                    "mber_PhonePrefixCode\" with the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 452
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ptbPhoneNu" +
                    "mber_PhoneSuffixCode\" with the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 453
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_lteEmailAd" +
                    "dress_TextBox\" with the value \"clientemail@variq.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 454
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 455
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Points of Contact Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("53-POC Summary")]
        public virtual void _53_POCSummary()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("53-POC Summary", ((string[])(null)));
#line 457
this.ScenarioSetup(scenarioInfo);
#line 458
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 459
 testRunner.When("I access the table using element id \"MainContentPlaceHolder_ucContacts_ContactsGr" +
                    "id\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 460
 testRunner.Then("table row number \"3\" column number \"1\" contains the value \"Web Service Client-LN\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 461
 testRunner.And("table row number \"3\" column number \"2\" contains the value \"Web Service Client-FN\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 462
 testRunner.And("table row number \"3\" column number \"4\" contains the value \"(301) 888 - 9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 463
 testRunner.And("table row number \"3\" column number \"6\" contains the value \"clientemail@variq.com\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("54-Navigate to Company Information")]
        public virtual void _54_NavigateToCompanyInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("54-Navigate to Company Information", ((string[])(null)));
#line 465
this.ScenarioSetup(scenarioInfo);
#line 466
 testRunner.Given("the page title is \"E-Verify: Client Wizard - Points of Contact Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 467
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 468
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("55-Verify Company Information")]
        [NUnit.Framework.TestCaseAttribute("VariQ Web Service Agent - Client", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123 Test Dr", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Rockville", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MD", new string[0])]
        [NUnit.Framework.TestCaseAttribute("00000", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MONTGOMERY", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123456789", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2,500 to 4,999", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Federal Government", new string[0])]
        [NUnit.Framework.TestCaseAttribute("721 - ACCOMMODATION (721)", new string[0])]
        public virtual void _55_VerifyCompanyInformation(string textOnPage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("55-Verify Company Information", exampleTags);
#line 470
this.ScenarioSetup(scenarioInfo);
#line 471
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 472
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("56-Register Client")]
        public virtual void _56_RegisterClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("56-Register Client", ((string[])(null)));
#line 487
this.ScenarioSetup(scenarioInfo);
#line 488
 testRunner.Given("the page title is \"E-Verify: Client Wizard - Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 489
 testRunner.When("I click on the submit button labeled \"Register Client\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 490
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Thank you for registering for E-Veri" +
                    "fy\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("57-Navigate to Newly Registered Client")]
        public virtual void _57_NavigateToNewlyRegisteredClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("57-Navigate to Newly Registered Client", ((string[])(null)));
#line 492
this.ScenarioSetup(scenarioInfo);
#line 493
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 494
 testRunner.When("I click on the link using element id \"anch_7\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 495
 testRunner.And("I click on the link containing the text \"View Existing Clients\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 496
 testRunner.And("I click on the submit button labeled \"Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 497
 testRunner.Then("the page title is \"E-Verify: Search Results\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("58-Verify newly created Client")]
        [NUnit.Framework.TestCaseAttribute("3", "VariQ Web Service Agent - Client", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "123 Test Dr", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "Rockville", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "MD", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "PENDING", new string[0])]
        public virtual void _58_VerifyNewlyCreatedClient(string tableRowNumber, string data, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("58-Verify newly created Client", exampleTags);
#line 499
this.ScenarioSetup(scenarioInfo);
#line 500
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 501
 testRunner.When("I access the table using element id \"MainContentPlaceHolder_ClientCompanyGrid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 502
 testRunner.Then(string.Format("table row number {0} contains the values {1} from the following table", tableRowNumber, data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("59-Logon to WebHQ and search for company - client")]
        public virtual void _59_LogonToWebHQAndSearchForCompany_Client()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("59-Logon to WebHQ and search for company - client", ((string[])(null)));
#line 512
this.ScenarioSetup(scenarioInfo);
#line 513
 testRunner.Given("I navigate to the url for \"webhq\" titled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 514
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 515
 testRunner.And("I click on the button using element id \"btnContinue1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 516
 testRunner.And("I set the text box using element id \"txtUserID\" with the value for \"webhq-usernam" +
                    "e\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 517
 testRunner.And("I set the text box using element id \"txtUserPassword\" with the value for \"webhq-p" +
                    "assword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 518
 testRunner.And("I click on the submit button labeled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 519
 testRunner.Then("the page title is \"Web-HQ: Home\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 520
 testRunner.And("I click on the link containing the text \"Maintain Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 521
 testRunner.And("the page title is \"Company Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 522
 testRunner.And("I set the text box using element id \"txtEmployer_TextBox\" with the value \"VariQ W" +
                    "eb Service Agent - Client\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 523
 testRunner.And("I click on the submit button labeled \"Display Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 524
 testRunner.Then("the page title is \"Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("60-Set Mou date for new client")]
        public virtual void _60_SetMouDateForNewClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("60-Set Mou date for new client", ((string[])(null)));
#line 526
this.ScenarioSetup(scenarioInfo);
#line 527
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 528
 testRunner.When("I access the table using tag \"table\" attribute type \"class\" attribute value \"Cont" +
                    "rolText\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 529
 testRunner.And("I save the table row number containing the data \"PENDING\" in column number \"11\" i" +
                    "nto the variable \"tableRowNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 530
 testRunner.And("I click on the button labeled \"Edit\" in the table row number saved in the variabl" +
                    "e \"tableRowNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 531
 testRunner.And("the page title is \"Client Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 532
 testRunner.And("I access table number \"5\" using tag \"table\" attribute type \"id\" attribute value \"" +
                    "tblAddress\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 533
 testRunner.And("I click on the button labeled \"View / Edit\" in row number \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 534
 testRunner.And("I set the text box using element id \"ucCompanyAccess_cdtMOUDate_dateTextBox\" with" +
                    " the value \"01/01/2016\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 535
 testRunner.And("I click on the submit button labeled \"Submit Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 536
 testRunner.Then("table row number \"2\" column number \"3\" contains the value \"01/01/2016\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("61-Finally logon to eVerify and validate new client activation")]
        public virtual void _61_FinallyLogonToEVerifyAndValidateNewClientActivation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("61-Finally logon to eVerify and validate new client activation", ((string[])(null)));
#line 538
this.ScenarioSetup(scenarioInfo);
#line 539
 testRunner.Given("I navigate to the url for \"everify\" titled \"E-Verify: Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 540
 testRunner.When("I click on the submit button containing the text \"I agree\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 541
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_UserIdTextBox_TextBox" +
                    "\" with the value stored in the variable \"userid1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 542
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_PasswordTextBox_TextB" +
                    "ox\" with the value \"Autotest123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 543
 testRunner.And("I click on the submit button labeled \"Log In\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 544
 testRunner.And("I click on the link using element id \"anch_7\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 545
 testRunner.And("I click on the link containing the text \"View Existing Clients\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 546
 testRunner.And("I click on the submit button labeled \"Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 547
 testRunner.And("I access the table using element id \"MainContentPlaceHolder_ClientCompanyGrid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 548
 testRunner.Then("table row number \"3\" column number \"2\" contains the value \"VariQ Web Service Agen" +
                    "t - Client\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 549
 testRunner.And("table row number \"3\" column number \"6\" contains the value \"ACTIVE\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 550
 testRunner.And("the page title is \"E-Verify: Search Results\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("62 - Logout of E-Verify")]
        public virtual void _62_LogoutOfE_Verify()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("62 - Logout of E-Verify", ((string[])(null)));
#line 552
this.ScenarioSetup(scenarioInfo);
#line 553
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 554
 testRunner.When("I click on the button using element id \"anch_32\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 555
 testRunner.Then("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
