// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Features.Enrollment
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Corporate Employer Enrollment")]
    public partial class CorporateEmployerEnrollmentFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CorporateEmployerEnrollment.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Corporate Employer Enrollment", @"		1.  Register Corporate Employer, Add a Corporate Administrator, Add a Location & Program Administrator and validate all.
		2.  Employer Registration Page & Review (Scenarios 01-06) 
		3.  Company & Corporate Administrator Informations (Scenarios 07,08)
		4.  Registration Review & Enroll  (Scenario 09,10)
		5.  Use WebHQ to edit and validate company, set MOU activation date, save Program Administrator ID, Set Tutorial Complete/Temp Password for Corporate Admin (Scenarios 21-28)
		6.  Login to everify as a Corporate Administrator (Scenario 29)
		7.  Validate the Program Administrator - New Password and Security Questions, Verify User Profile (Scenarios 30-31)
		8.  Add a New Location (Scenario 32)
		9.  Organization Designation, MOU Signatory, Company Informations, Program Administrator Informations, Registration Review & Enroll (Scenarios 33-44)
		10. Use WebHQ to edit and validate Location, Program Administrator - set MOU activation date, save Program Administrator ID, Set Tutorial Complete/Temp Password for Corporate Admin (Scenarios 45-52)
		11. Login to eVerify as a Program Administrator (Scenario 53)
		12. Verify Program Administration activation - Submit New Password and Security Questions, Verify User Profile (Scenarios 54-56)", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01-Navigate to Employer Registration page")]
        public virtual void _01_NavigateToEmployerRegistrationPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01-Navigate to Employer Registration page", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.Given("I navigate to the url for \"registration\" titled \"E-Verify – Employer Registration" +
                    " – Start Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
 testRunner.And("I click on the submit button labeled \"Continue\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Checklist\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02-Employer Registration - Checklist")]
        public virtual void _02_EmployerRegistration_Checklist()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02-Employer Registration - Checklist", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 23
 testRunner.When("I click on the submit button labeled \"Begin E-Verify Enrollment\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Start Here\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03-Employer Access-Y Agent-N Corporate-Y Web Services-N")]
        public virtual void _03_EmployerAccess_YAgent_NCorporate_YWebServices_N()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03-Employer Access-Y Agent-N Corporate-Y Web Services-N", ((string[])(null)));
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
 testRunner.When("I click on the radio button using element id \"radBpYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
 testRunner.And("I click on the radio button using element id \"radDaNo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("I click on the radio button using element id \"radCorpYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And("I click on the radio button using element id \"radWsNo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.Then("the page title is \"E-Verify - Employer Registration - Let’s Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04-Registration Review Page Verification")]
        public virtual void _04_RegistrationReviewPageVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04-Registration Review Page Verification", ((string[])(null)));
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
 testRunner.When("I access the table using tag \"div\" attribute type \"class\" attribute value \"box\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05 - Registration Review Table Verification")]
        [NUnit.Framework.TestCaseAttribute("2", "Yes", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "No", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4", "Yes", new string[0])]
        [NUnit.Framework.TestCaseAttribute("5", "No", new string[0])]
        public virtual void _05_RegistrationReviewTableVerification(string row, string answer, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 - Registration Review Table Verification", exampleTags);
#line 39
this.ScenarioSetup(scenarioInfo);
#line 40
 testRunner.Then(string.Format("table row number {0} contains the values {1} from the following table", row, answer), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06-Registration Review Page")]
        public virtual void _06_RegistrationReviewPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06-Registration Review Page", ((string[])(null)));
#line 49
this.ScenarioSetup(scenarioInfo);
#line 50
 testRunner.Given("the page title is \"E-Verify - Employer Registration - Let’s Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 51
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07-Company Information")]
        public virtual void _07_CompanyInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07-Company Information", ((string[])(null)));
#line 54
this.ScenarioSetup(scenarioInfo);
#line 55
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 56
 testRunner.When("I set the text box using element id \"ucCAAddressAdmin_txtParentName_TextBox\" with" +
                    " the value \"CorporateEmployer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
 testRunner.And("I set the text box using element id \"ucCAAddressAdmin_txtAddress1_TextBox\" with t" +
                    "he value \"123 Automation Drive\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.And("I set the text box using element id \"ucCAAddressAdmin_txtCity_TextBox\" with the v" +
                    "alue \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.And("I select the drop down text \"MARYLAND\" using element id \"ucCAAddressAdmin_vssStat" +
                    "e_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.And("I set the text box using element id \"ucCAAddressAdmin_ltzZipCode_TextBox\" with th" +
                    "e value \"20852\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
 testRunner.And("I select the drop down text \"MONTGOMERY\" using element id \"ucCAAddressAdmin_vscCo" +
                    "unty_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
 testRunner.Then("the page title is \"E-Verify – Employer Registration - Corporate Administrator Use" +
                    "rs\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08 - Corporate Administrator Details")]
        public virtual void _08_CorporateAdministratorDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08 - Corporate Administrator Details", ((string[])(null)));
#line 65
this.ScenarioSetup(scenarioInfo);
#line 66
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 67
 testRunner.When("I set the text box using element id \"ucCorpPocs_rptContacts__ctl0_ltLastName_Text" +
                    "Box\" with the value \"CO-Employer User-LN-One\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 68
 testRunner.And("I set the text box using element id \"ucCorpPocs_rptContacts__ctl0_ltFirstName_Tex" +
                    "tBox\" with the value \"CO-Employer User-FN-One\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.And("I set the text box using element id \"ucCorpPocs_rptContacts__ctl0_scPhone_PhoneAr" +
                    "eaCode\" with the value \"777\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
 testRunner.And("I set the text box using element id \"ucCorpPocs_rptContacts__ctl0_scPhone_PhonePr" +
                    "efixCode\" with the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
 testRunner.And("I set the text box using element id \"ucCorpPocs_rptContacts__ctl0_scPhone_PhoneSu" +
                    "ffixCode\" with the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
 testRunner.And("I set the text box using element id \"ucCorpPocs_rptContacts__ctl0_ltEmail_TextBox" +
                    "\" with the value \"testuser1@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 73
 testRunner.And("I set the text box using element id \"ucCorpPocs_rptContacts__ctl0_ltEmail2_TextBo" +
                    "x\" with the value \"testuser1@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Registration Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("09-Registration Review-Verify Registration Details")]
        [NUnit.Framework.TestCaseAttribute("CorporateEmployer", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123 Automation Drive", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Rockville", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MD", new string[0])]
        [NUnit.Framework.TestCaseAttribute("20852", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MONTGOMERY", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CO-Employer User-LN-One", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CO-Employer User-FN-One", new string[0])]
        [NUnit.Framework.TestCaseAttribute("(777) 888 - 9999", new string[0])]
        [NUnit.Framework.TestCaseAttribute("testuser1@test.com", new string[0])]
        public virtual void _09_RegistrationReview_VerifyRegistrationDetails(string textOnPage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09-Registration Review-Verify Registration Details", exampleTags);
#line 77
this.ScenarioSetup(scenarioInfo);
#line 78
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 79
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10-Complete Enrollment to Register Corporate Employer")]
        public virtual void _10_CompleteEnrollmentToRegisterCorporateEmployer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10-Complete Enrollment to Register Corporate Employer", ((string[])(null)));
#line 94
this.ScenarioSetup(scenarioInfo);
#line 95
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Registration Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 96
 testRunner.When("I set the checkbox with element id \"ucCAAddressAdminRegResults_chkAgree\" to \"true" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 97
 testRunner.And("I click on the submit button labeled \"Register Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
 testRunner.Then("the page title is \"E-Verify – Employer Registration – You\'re Finished\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11-Navigate to Employer Registration page")]
        public virtual void _11_NavigateToEmployerRegistrationPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11-Navigate to Employer Registration page", ((string[])(null)));
#line 100
this.ScenarioSetup(scenarioInfo);
#line 101
 testRunner.Given("I navigate to the url for \"registration\" titled \"E-Verify – Employer Registration" +
                    " – Start Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 102
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 103
 testRunner.And("I click on the submit button labeled \"Continue\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 104
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Checklist\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("12-Employer Registration - Checklist")]
        public virtual void _12_EmployerRegistration_Checklist()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12-Employer Registration - Checklist", ((string[])(null)));
#line 106
this.ScenarioSetup(scenarioInfo);
#line 107
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 108
 testRunner.When("I click on the submit button labeled \"Begin E-Verify Enrollment\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 109
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Start Here\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("13-Employer Access-Y Agent-N Corporate-Y Web Services-N")]
        public virtual void _13_EmployerAccess_YAgent_NCorporate_YWebServices_N()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13-Employer Access-Y Agent-N Corporate-Y Web Services-N", ((string[])(null)));
#line 111
this.ScenarioSetup(scenarioInfo);
#line 112
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 113
 testRunner.When("I click on the radio button using element id \"radBpYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 114
 testRunner.And("I click on the radio button using element id \"radDaNo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 115
 testRunner.And("I click on the radio button using element id \"radCorpYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 116
 testRunner.And("I click on the radio button using element id \"radWsNo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 117
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
 testRunner.Then("the page title is \"E-Verify - Employer Registration - Let’s Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("14-Registration Review Page Verification")]
        public virtual void _14_RegistrationReviewPageVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14-Registration Review Page Verification", ((string[])(null)));
#line 120
this.ScenarioSetup(scenarioInfo);
#line 121
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 122
 testRunner.When("I access the table using tag \"div\" attribute type \"class\" attribute value \"box\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("15 - Registration Review Table Verification")]
        [NUnit.Framework.TestCaseAttribute("2", "Yes", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "No", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4", "Yes", new string[0])]
        [NUnit.Framework.TestCaseAttribute("5", "No", new string[0])]
        public virtual void _15_RegistrationReviewTableVerification(string row, string answer, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("15 - Registration Review Table Verification", exampleTags);
#line 124
this.ScenarioSetup(scenarioInfo);
#line 125
 testRunner.Then(string.Format("table row number {0} contains the values {1} from the following table", row, answer), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("16-Registration Review Page")]
        public virtual void _16_RegistrationReviewPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("16-Registration Review Page", ((string[])(null)));
#line 134
this.ScenarioSetup(scenarioInfo);
#line 135
 testRunner.Given("the page title is \"E-Verify - Employer Registration - Let’s Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 136
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 137
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("17-Company Information")]
        public virtual void _17_CompanyInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("17-Company Information", ((string[])(null)));
#line 139
this.ScenarioSetup(scenarioInfo);
#line 140
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 141
 testRunner.When("I set the text box using element id \"ucCAAddressAdmin_txtParentName_TextBox\" with" +
                    " the value \"CorporateEmployer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 142
 testRunner.And("I set the text box using element id \"ucCAAddressAdmin_txtAddress1_TextBox\" with t" +
                    "he value \"123 Automation Drive\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 143
 testRunner.And("I set the text box using element id \"ucCAAddressAdmin_txtCity_TextBox\" with the v" +
                    "alue \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 144
 testRunner.And("I select the drop down text \"MARYLAND\" using element id \"ucCAAddressAdmin_vssStat" +
                    "e_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 145
 testRunner.And("I set the text box using element id \"ucCAAddressAdmin_ltzZipCode_TextBox\" with th" +
                    "e value \"20852\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 146
 testRunner.And("I select the drop down text \"MONTGOMERY\" using element id \"ucCAAddressAdmin_vscCo" +
                    "unty_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 147
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 148
 testRunner.Then("the page title is \"E-Verify – Employer Registration - Corporate Administrator Use" +
                    "rs\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("18 - Corporate Administrator Details")]
        public virtual void _18_CorporateAdministratorDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("18 - Corporate Administrator Details", ((string[])(null)));
#line 150
this.ScenarioSetup(scenarioInfo);
#line 151
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 152
 testRunner.When("I set the text box using element id \"ucCorpPocs_rptContacts__ctl0_ltLastName_Text" +
                    "Box\" with the value \"CO-Employer User-LN-One\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 153
 testRunner.And("I set the text box using element id \"ucCorpPocs_rptContacts__ctl0_ltFirstName_Tex" +
                    "tBox\" with the value \"CO-Employer User-FN-One\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 154
 testRunner.And("I set the text box using element id \"ucCorpPocs_rptContacts__ctl0_scPhone_PhoneAr" +
                    "eaCode\" with the value \"777\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 155
 testRunner.And("I set the text box using element id \"ucCorpPocs_rptContacts__ctl0_scPhone_PhonePr" +
                    "efixCode\" with the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 156
 testRunner.And("I set the text box using element id \"ucCorpPocs_rptContacts__ctl0_scPhone_PhoneSu" +
                    "ffixCode\" with the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 157
 testRunner.And("I set the text box using element id \"ucCorpPocs_rptContacts__ctl0_ltEmail_TextBox" +
                    "\" with the value \"testuser1@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 158
 testRunner.And("I set the text box using element id \"ucCorpPocs_rptContacts__ctl0_ltEmail2_TextBo" +
                    "x\" with the value \"testuser1@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 160
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Registration Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("19-Registration Review-Verify Registration Details")]
        [NUnit.Framework.TestCaseAttribute("CorporateEmployer", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123 Automation Drive", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Rockville", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MD", new string[0])]
        [NUnit.Framework.TestCaseAttribute("20852", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MONTGOMERY", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CO-Employer User-LN-One", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CO-Employer User-FN-One", new string[0])]
        [NUnit.Framework.TestCaseAttribute("(777) 888 - 9999", new string[0])]
        [NUnit.Framework.TestCaseAttribute("testuser1@test.com", new string[0])]
        public virtual void _19_RegistrationReview_VerifyRegistrationDetails(string textOnPage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("19-Registration Review-Verify Registration Details", exampleTags);
#line 162
this.ScenarioSetup(scenarioInfo);
#line 163
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 164
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("20-Complete Enrollment to Register Corporate Employer")]
        public virtual void _20_CompleteEnrollmentToRegisterCorporateEmployer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("20-Complete Enrollment to Register Corporate Employer", ((string[])(null)));
#line 179
this.ScenarioSetup(scenarioInfo);
#line 180
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Registration Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 181
 testRunner.When("I set the checkbox with element id \"ucCAAddressAdminRegResults_chkAgree\" to \"true" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 182
 testRunner.And("I click on the submit button labeled \"Register Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 183
 testRunner.Then("the page title is \"E-Verify – Employer Registration – You\'re Finished\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("21-Logon to WebHQ")]
        public virtual void _21_LogonToWebHQ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("21-Logon to WebHQ", ((string[])(null)));
#line 185
this.ScenarioSetup(scenarioInfo);
#line 186
 testRunner.Given("I navigate to the url for \"webhq\" titled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 187
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 188
 testRunner.And("I click on the button using element id \"btnContinue1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 189
 testRunner.And("I set the text box using element id \"txtUserID\" with the value for \"webhq-usernam" +
                    "e\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 190
 testRunner.And("I set the text box using element id \"txtUserPassword\" with the value for \"webhq-p" +
                    "assword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 191
 testRunner.And("I click on the submit button labeled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 192
 testRunner.Then("the page title is \"Web-HQ: Home\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("22-Search Company")]
        public virtual void _22_SearchCompany()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("22-Search Company", ((string[])(null)));
#line 194
this.ScenarioSetup(scenarioInfo);
#line 195
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 196
 testRunner.When("I click on the link containing the text \"Maintain Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 197
 testRunner.And("the page title is \"Company Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 198
 testRunner.And("I set the text box using element id \"txtEmployer_TextBox\" with the value \"Corpora" +
                    "teEmployer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 199
 testRunner.And("I click on the submit button labeled \"Display Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 200
 testRunner.Then("the page title is \"Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("23-Navigate to Company details")]
        public virtual void _23_NavigateToCompanyDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("23-Navigate to Company details", ((string[])(null)));
#line 202
this.ScenarioSetup(scenarioInfo);
#line 203
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 204
 testRunner.When("I access the table using tag \"table\" attribute type \"class\" attribute value \"Cont" +
                    "rolText\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 205
 testRunner.And("I save the table row number containing the data \"PENDING\" in column number \"11\" i" +
                    "nto the variable \"tableRowNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 206
 testRunner.And("I click on the button labeled \"Edit\" in the table row number saved in the variabl" +
                    "e \"tableRowNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 207
 testRunner.Then("the page title is \"ParentSummary\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("24-Validate and Match Company")]
        public virtual void _24_ValidateAndMatchCompany()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("24-Validate and Match Company", ((string[])(null)));
#line 209
this.ScenarioSetup(scenarioInfo);
#line 210
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 211
 testRunner.When("I click on the submit button labeled \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 212
 testRunner.And("the page title is \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 213
 testRunner.And("I skip scenario if element is missing using tag \"input\" attribute type \"value\" at" +
                    "tribute value \"Confirm Company Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 214
 testRunner.And("I click on the submit button labeled \"Confirm Company Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 215
 testRunner.And("I select the drop down text \"Match\" using element id \"vscMatchStatus_SelectorDrop" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 216
 testRunner.And("I click on the submit button labeled \"Confirm Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 217
 testRunner.And("the page title is \"ParentSummary\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 218
 testRunner.And("I click on the submit button labeled \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 219
 testRunner.And("I access table number \"2\" using tag \"table\" attribute type \"id\" attribute value \"" +
                    "structure\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 220
 testRunner.Then("table row number \"1\" column number \"2\" contains the value \"Match\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("25-Set MOU Signed Date & Check Status")]
        public virtual void _25_SetMOUSignedDateCheckStatus()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("25-Set MOU Signed Date & Check Status", ((string[])(null)));
#line 222
this.ScenarioSetup(scenarioInfo);
#line 223
 testRunner.Given("the page title is \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 224
 testRunner.When("I click on the submit button labeled \"Return to Maintain Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 225
 testRunner.And("the page title is \"ParentSummary\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 226
 testRunner.And("I click on the button using element id \"btnAccessInfo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 227
 testRunner.And("the page title is \"Corporate Maintenance\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 228
 testRunner.And("I set the text box using element id \"cdtStartDate_dateTextBox\" with the value \"06" +
                    "/20/2016\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 229
 testRunner.And("I click on the submit button labeled \"Submit Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 230
 testRunner.Then("the page title is \"ParentSummary\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("26-Save Active User ID and Edit User")]
        public virtual void _26_SaveActiveUserIDAndEditUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("26-Save Active User ID and Edit User", ((string[])(null)));
#line 232
this.ScenarioSetup(scenarioInfo);
#line 233
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 234
 testRunner.When("I click on the button using element id \"btnUser\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 235
 testRunner.And("the page title is \"Employer User Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 236
 testRunner.And("I access the table using element id \"dgCpsUsers\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 237
 testRunner.And("I save the data from table row number \"3\" column number \"2\" into the variable \"us" +
                    "erid1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 238
 testRunner.And("I click on table row number \"3\" in column number \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 239
 testRunner.Then("the page title is \"User Details - View / Modify User Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("27-Set Tutorial Complete/Temp Password for Corporate Admin")]
        public virtual void _27_SetTutorialCompleteTempPasswordForCorporateAdmin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("27-Set Tutorial Complete/Temp Password for Corporate Admin", ((string[])(null)));
#line 241
this.ScenarioSetup(scenarioInfo);
#line 242
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 243
 testRunner.When("I set the checkbox with element id \"ucCpsUserModEmployer_chkTutorialComplete\" to " +
                    "\"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 244
 testRunner.And("I set the text box using element id \"ucCpsUserModEmployer_ltbNewPwd_TextBox\" with" +
                    " the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 245
 testRunner.And("I set the text box using element id \"ucCpsUserModEmployer_ltbConfPwd_TextBox\" wit" +
                    "h the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 246
 testRunner.And("I click on the submit button labeled \"Submit User Modifications\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 247
 testRunner.Then("the page title is \"User Confirmation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("28-Signout from Web-HQ")]
        public virtual void _28_SignoutFromWeb_HQ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("28-Signout from Web-HQ", ((string[])(null)));
#line 249
this.ScenarioSetup(scenarioInfo);
#line 250
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 251
 testRunner.When("I click on the button using element id \"ucVisNav_hlExit\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 252
 testRunner.Then("the page title is \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 253
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("29-Logon to eVerify as Corp.Admin. to create Location/Program Admin.")]
        public virtual void _29_LogonToEVerifyAsCorp_Admin_ToCreateLocationProgramAdmin_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("29-Logon to eVerify as Corp.Admin. to create Location/Program Admin.", ((string[])(null)));
#line 255
this.ScenarioSetup(scenarioInfo);
#line 256
 testRunner.Given("I navigate to the url for \"everify\" titled \"E-Verify: Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 257
 testRunner.When("I click on the submit button containing the text \"I agree\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 258
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_UserIdTextBox_TextBox" +
                    "\" with the value stored in the variable \"userid1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 259
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_PasswordTextBox_TextB" +
                    "ox\" with the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 260
 testRunner.And("I click on the submit button labeled \"Log In\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 261
 testRunner.Then("the page title is \"E-Verify: Change Password\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("30-Submit New Password and Security Questions")]
        public virtual void _30_SubmitNewPasswordAndSecurityQuestions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("30-Submit New Password and Security Questions", ((string[])(null)));
#line 263
this.ScenarioSetup(scenarioInfo);
#line 264
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 265
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_ltbOldPwd_TextBox\" wi" +
                    "th the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 266
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ltbNewPwd_TextBox\" wi" +
                    "th the value \"Autotest123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 267
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ltbValidatePwd_TextBo" +
                    "x\" with the value \"Autotest123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 268
 testRunner.And("I select the drop down text \"What is the name of the first school you attended?\" " +
                    "using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 269
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer1_TextBox\" with the value \"abcde\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 270
 testRunner.And("I select the drop down text \"What is the name of your first pet?\" using element i" +
                    "d \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 271
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer2_TextBox\" with the value \"fghij\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 272
 testRunner.And("I select the drop down text \"What is your father\'s middle name?\" using element id" +
                    " \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 273
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer3_TextBox\" with the value \"klmno\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 274
 testRunner.And("I click on the submit button labeled \"Submit\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 275
 testRunner.Then("the page title is \"E-Verify: Update User Profile\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("31-Verify Corporate Administrator Profile")]
        public virtual void _31_VerifyCorporateAdministratorProfile()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("31-Verify Corporate Administrator Profile", ((string[])(null)));
#line 277
this.ScenarioSetup(scenarioInfo);
#line 278
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 279
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhoneAreaCode\" contains the value \"777\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 280
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhonePrefixCode\" contains the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 281
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhoneSuffixCode\" contains the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 282
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_lteUs" +
                    "erEmail_TextBox\" contains the value \"testuser1@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 283
 testRunner.When("I click on the submit button labeled \"Submit User Profile Changes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 284
 testRunner.Then("the page title is \"E-Verify: Home Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("32-Click Add New Location under Company Locations")]
        public virtual void _32_ClickAddNewLocationUnderCompanyLocations()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("32-Click Add New Location under Company Locations", ((string[])(null)));
#line 286
this.ScenarioSetup(scenarioInfo);
#line 287
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 288
 testRunner.When("I click on the button using element id \"anch_3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 289
 testRunner.And("I click on the link containing the text \"Add New Location\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 290
 testRunner.Then("the page title is \"E-Verify: Employer Wizard - Organization Designation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("33-Organization Designation")]
        public virtual void _33_OrganizationDesignation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("33-Organization Designation", ((string[])(null)));
#line 292
this.ScenarioSetup(scenarioInfo);
#line 293
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 294
 testRunner.When("I select the drop down text \"Federal Government\" using element id \"MainContentPla" +
                    "ceHolder_EmployerCategory1_ddlCategory\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 295
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 296
 testRunner.Then("the page title is \"E-Verify: Employer Wizard - MOU Notice\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("34-Switch to iFrame to verify data")]
        public virtual void _34_SwitchToIFrameToVerifyData()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("34-Switch to iFrame to verify data", ((string[])(null)));
#line 298
this.ScenarioSetup(scenarioInfo);
#line 299
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 300
 testRunner.When("I switch to iframe using element id \"MainContentPlaceHolder_MouNotice_frmMou\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 301
 testRunner.Then("the page contains the text \"MEMORANDUM OF UNDERSTANDING\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 302
 testRunner.And("I switch back to the body of the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("35-Memorandum of Understanding (MOU)")]
        public virtual void _35_MemorandumOfUnderstandingMOU()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("35-Memorandum of Understanding (MOU)", ((string[])(null)));
#line 304
this.ScenarioSetup(scenarioInfo);
#line 305
 testRunner.Given("the page title is \"E-Verify: Employer Wizard - MOU Notice\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 306
 testRunner.When("I click on the radio button using element id \"MainContentPlaceHolder_MouNotice_ra" +
                    "dAccept\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 307
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 308
 testRunner.Then("the page title is \"E-Verify: Employer Wizard - Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("36-Company Details for the Location")]
        public virtual void _36_CompanyDetailsForTheLocation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("36-Company Details for the Location", ((string[])(null)));
#line 310
this.ScenarioSetup(scenarioInfo);
#line 311
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 312
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_t" +
                    "xtEmpName_TextBox\" with the value \"CorporateEmployer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 313
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_t" +
                    "xtAddress1_TextBox\" with the value \"123 Automation Drive\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 314
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_t" +
                    "xtCity_TextBox\" with the value \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 315
 testRunner.And("I select the drop down text \"MARYLAND\" using element id \"MainContentPlaceHolder_C" +
                    "ompanyInformation1_ddlState\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 316
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_l" +
                    "tzZipCode_TextBox\" with the value \"20852\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 317
 testRunner.And("I select the drop down text \"MONTGOMERY\" using element id \"MainContentPlaceHolder" +
                    "_CompanyInformation1_ddlCounty\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 318
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_l" +
                    "tnEmployerId_TextBox\" with the value \"123456789\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 319
 testRunner.And("I select the drop down text \"100 to 499\" using element id \"MainContentPlaceHolder" +
                    "_CompanyInformation1_ddlTotalEmployeeRange\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 320
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 321
 testRunner.Then("the page title is \"E-Verify: Employer Wizard - Enter NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("37 - NAICS Code for new Web Service Employer")]
        public virtual void _37_NAICSCodeForNewWebServiceEmployer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("37 - NAICS Code for new Web Service Employer", ((string[])(null)));
#line 323
this.ScenarioSetup(scenarioInfo);
#line 324
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 325
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_Naics_ltNaicsCode_Tex" +
                    "tBox\" with the value \"521\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 326
 testRunner.And("I click on the submit button labeled \"Accept NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 327
 testRunner.Then("the page title is \"E-Verify: Employer Wizard - How Many Hiring Sites?\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("38-Hiring Sites Verification")]
        public virtual void _38_HiringSitesVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("38-Hiring Sites Verification", ((string[])(null)));
#line 329
this.ScenarioSetup(scenarioInfo);
#line 330
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 331
 testRunner.When("I click on the submit button labeled \"Single Site Verification\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 332
 testRunner.Then("the page title is \"E-Verify: Employer Wizard - Enter Program Administrator\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("39-Program Administrator Details")]
        public virtual void _39_ProgramAdministratorDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("39-Program Administrator Details", ((string[])(null)));
#line 334
this.ScenarioSetup(scenarioInfo);
#line 335
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 336
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ltaLastNam" +
                    "e_TextBox\" with the value \"AO-Corporate Employer User-LN-One\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 337
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ltaFirstNa" +
                    "me_TextBox\" with the value \"AO-Corp Empl User-FN-One\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 338
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ptbPhoneNu" +
                    "mber_PhoneAreaCode\" with the value \"777\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 339
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ptbPhoneNu" +
                    "mber_PhonePrefixCode\" with the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 340
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ptbPhoneNu" +
                    "mber_PhoneSuffixCode\" with the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 341
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_lteEmailAd" +
                    "dress_TextBox\" with the value \"testuser2@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 342
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 343
 testRunner.Then("the page title is \"E-Verify: Employer Wizard - Points of Contact Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("40-Point of Contact/Program Adminintrator Summary List")]
        [NUnit.Framework.TestCaseAttribute("AO-Corporate Employer User-LN-One", new string[0])]
        [NUnit.Framework.TestCaseAttribute("AO-Corp Empl User-FN-One", new string[0])]
        [NUnit.Framework.TestCaseAttribute("(777) 888 - 9999", new string[0])]
        [NUnit.Framework.TestCaseAttribute("testuser2@test.com", new string[0])]
        public virtual void _40_PointOfContactProgramAdminintratorSummaryList(string textOnPage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40-Point of Contact/Program Adminintrator Summary List", exampleTags);
#line 345
this.ScenarioSetup(scenarioInfo);
#line 346
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 347
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("41-POC/Program Admin confirmation")]
        public virtual void _41_POCProgramAdminConfirmation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41-POC/Program Admin confirmation", ((string[])(null)));
#line 356
this.ScenarioSetup(scenarioInfo);
#line 357
 testRunner.Given("the page title is \"E-Verify: Employer Wizard - Points of Contact Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 358
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 359
 testRunner.Then("the page title is \"E-Verify: Employer Wizard - Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("42-Company Information-Review")]
        [NUnit.Framework.TestCaseAttribute("CorporateEmployer", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123 Automation Drive", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Rockville", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MD", new string[0])]
        [NUnit.Framework.TestCaseAttribute("20852", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MONTGOMERY", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123456789", new string[0])]
        [NUnit.Framework.TestCaseAttribute("100 to 499", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CorporateEmployer", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Federal Government", new string[0])]
        public virtual void _42_CompanyInformation_Review(string textOnPage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("42-Company Information-Review", exampleTags);
#line 361
this.ScenarioSetup(scenarioInfo);
#line 362
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 363
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("43-Register Employer")]
        public virtual void _43_RegisterEmployer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("43-Register Employer", ((string[])(null)));
#line 378
this.ScenarioSetup(scenarioInfo);
#line 379
 testRunner.Given("the page title is \"E-Verify: Employer Wizard - Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 380
 testRunner.When("I click on the submit button labeled \"Register Employer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 381
 testRunner.Then("the page title is \"E-Verify: Employer Wizard - Thank you for registering for E-Ve" +
                    "rify\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("44-Logout of E-verify")]
        public virtual void _44_LogoutOfE_Verify()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("44-Logout of E-verify", ((string[])(null)));
#line 383
this.ScenarioSetup(scenarioInfo);
#line 384
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 385
 testRunner.When("I click on the link using element id \"anch_26\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 386
 testRunner.Then("the page title is \"E-Verify: Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 387
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("45-Logon to WebHQ")]
        public virtual void _45_LogonToWebHQ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("45-Logon to WebHQ", ((string[])(null)));
#line 389
this.ScenarioSetup(scenarioInfo);
#line 390
 testRunner.Given("I navigate to the url for \"webhq\" titled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 391
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 392
 testRunner.And("I click on the button using element id \"btnContinue1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 393
 testRunner.And("I set the text box using element id \"txtUserID\" with the value for \"webhq-usernam" +
                    "e\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 394
 testRunner.And("I set the text box using element id \"txtUserPassword\" with the value for \"webhq-p" +
                    "assword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 395
 testRunner.And("I click on the submit button labeled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 396
 testRunner.Then("the page title is \"Web-HQ: Home\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("46-Search Company - Location")]
        public virtual void _46_SearchCompany_Location()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("46-Search Company - Location", ((string[])(null)));
#line 398
this.ScenarioSetup(scenarioInfo);
#line 399
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 400
 testRunner.When("I click on the link containing the text \"Maintain Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 401
 testRunner.And("the page title is \"Company Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 402
 testRunner.And("I set the text box using element id \"txtEmployer_TextBox\" with the value \"Corpora" +
                    "teEmployer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 403
 testRunner.And("I click on the submit button labeled \"Display Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 404
 testRunner.Then("the page title is \"Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("47-Navigate to Company details")]
        public virtual void _47_NavigateToCompanyDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("47-Navigate to Company details", ((string[])(null)));
#line 406
this.ScenarioSetup(scenarioInfo);
#line 407
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 408
 testRunner.When("I access the table using tag \"table\" attribute type \"class\" attribute value \"Cont" +
                    "rolText\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 409
 testRunner.And("I save the table row number containing the data \"CorporateEmployer\" in column num" +
                    "ber \"3\" into the variable \"tableRowNumber1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 410
 testRunner.And("I click on the button labeled \"Edit\" in the table row number saved in the variabl" +
                    "e \"tableRowNumber1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 411
 testRunner.Then("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 412
 testRunner.And("the page contains the text \"WEB-BP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("48-IIP Match for Corporate Employer - Location")]
        public virtual void _48_IIPMatchForCorporateEmployer_Location()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("48-IIP Match for Corporate Employer - Location", ((string[])(null)));
#line 414
this.ScenarioSetup(scenarioInfo);
#line 415
 testRunner.Given("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 416
 testRunner.When("I click on the submit button labeled \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 417
 testRunner.And("the page title is \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 418
 testRunner.And("I skip scenario if element is missing using tag \"input\" attribute type \"value\" at" +
                    "tribute value \"Confirm Company Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 419
 testRunner.And("I click on the submit button labeled \"Confirm Company Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 420
 testRunner.And("I select the drop down text \"Match\" using element id \"vscMatchStatus_SelectorDrop" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 421
 testRunner.And("I click on the submit button labeled \"Confirm Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 422
 testRunner.And("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 423
 testRunner.And("I click on the submit button labeled \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 424
 testRunner.And("I access table number \"2\" using tag \"table\" attribute type \"id\" attribute value \"" +
                    "structure\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 425
 testRunner.Then("table row number \"1\" column number \"2\" contains the value \"Match\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("49-Set MOU Signed Date & Check Status")]
        public virtual void _49_SetMOUSignedDateCheckStatus()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("49-Set MOU Signed Date & Check Status", ((string[])(null)));
#line 427
this.ScenarioSetup(scenarioInfo);
#line 428
 testRunner.Given("the page title is \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 429
 testRunner.When("I click on the submit button labeled \"Return to Maintain Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 430
 testRunner.And("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 431
 testRunner.And("I click on the button using element id \"ucSummary_btnAccessInfo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 432
 testRunner.And("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 433
 testRunner.And("I set the text box using element id \"ucCompanyAccess_cdtMOUDate_dateTextBox\" with" +
                    " the value \"06/20/2016\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 434
 testRunner.And("I click on the submit button labeled \"Submit Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 435
 testRunner.Then("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("50-Save Active Program Administrator ID and Edit Program Administrator")]
        public virtual void _50_SaveActiveProgramAdministratorIDAndEditProgramAdministrator()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("50-Save Active Program Administrator ID and Edit Program Administrator", ((string[])(null)));
#line 437
this.ScenarioSetup(scenarioInfo);
#line 438
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 439
 testRunner.When("I click on the button using element id \"ucSummary_btnUser\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 440
 testRunner.And("the page title is \"Employer User Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 441
 testRunner.And("I access the table using element id \"dgCpsUsers\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 442
 testRunner.And("I save the data from table row number \"3\" column number \"2\" into the variable \"us" +
                    "erid2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 443
 testRunner.And("I click on table row number \"3\" in column number \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 444
 testRunner.Then("the page title is \"User Details - View / Modify User Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("51-Set Tutorial Complete/Temp Password for Program Admin")]
        public virtual void _51_SetTutorialCompleteTempPasswordForProgramAdmin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("51-Set Tutorial Complete/Temp Password for Program Admin", ((string[])(null)));
#line 446
this.ScenarioSetup(scenarioInfo);
#line 447
 testRunner.Given("the page title is \"User Details - View / Modify User Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 448
 testRunner.When("I set the checkbox with element id \"ucCpsUserModEmployer_chkTutorialComplete\" to " +
                    "\"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 449
 testRunner.And("I set the text box using element id \"ucCpsUserModEmployer_ltbNewPwd_TextBox\" with" +
                    " the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 450
 testRunner.And("I set the text box using element id \"ucCpsUserModEmployer_ltbConfPwd_TextBox\" wit" +
                    "h the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 451
 testRunner.And("I click on the submit button labeled \"Submit User Modifications\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 452
 testRunner.Then("the page title is \"User Details - User Confirmation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("52-Signout from Web-HQ")]
        public virtual void _52_SignoutFromWeb_HQ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("52-Signout from Web-HQ", ((string[])(null)));
#line 454
this.ScenarioSetup(scenarioInfo);
#line 455
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 456
 testRunner.When("I click on the button using element id \"ucVisNav_hlExit\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 457
 testRunner.Then("the page title is \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 458
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("53-Logon to eVerify as Prog.Admin. to change password")]
        public virtual void _53_LogonToEVerifyAsProg_Admin_ToChangePassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("53-Logon to eVerify as Prog.Admin. to change password", ((string[])(null)));
#line 460
this.ScenarioSetup(scenarioInfo);
#line 461
 testRunner.Given("I navigate to the url for \"everify\" titled \"E-Verify: Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 462
 testRunner.When("I click on the submit button containing the text \"I agree\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 463
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_UserIdTextBox_TextBox" +
                    "\" with the value stored in the variable \"userid2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 464
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_PasswordTextBox_TextB" +
                    "ox\" with the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 465
 testRunner.Then("the page title is \"E-Verify: Change Password\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("54-Submit New Password and Security Questions")]
        public virtual void _54_SubmitNewPasswordAndSecurityQuestions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("54-Submit New Password and Security Questions", ((string[])(null)));
#line 467
this.ScenarioSetup(scenarioInfo);
#line 468
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 469
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_ltbOldPwd_TextBox\" wi" +
                    "th the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 470
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ltbNewPwd_TextBox\" wi" +
                    "th the value \"Autotest123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 471
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ltbValidatePwd_TextBo" +
                    "x\" with the value \"Autotest123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 472
 testRunner.And("I select the drop down text \"What is the name of the first school you attended?\" " +
                    "using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 473
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer1_TextBox\" with the value \"abcde\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 474
 testRunner.And("I select the drop down text \"What is the name of your first pet?\" using element i" +
                    "d \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 475
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer2_TextBox\" with the value \"fghij\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 476
 testRunner.And("I select the drop down text \"What is your father\'s middle name?\" using element id" +
                    " \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 477
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer3_TextBox\" with the value \"klmno\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 478
 testRunner.And("I click on the submit button labeled \"Submit\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 479
 testRunner.Then("the page title is \"E-Verify: Update User Profile\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("55-Verify User Profile and logon to eVerify")]
        public virtual void _55_VerifyUserProfileAndLogonToEVerify()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("55-Verify User Profile and logon to eVerify", ((string[])(null)));
#line 481
this.ScenarioSetup(scenarioInfo);
#line 482
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 483
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhoneAreaCode\" contains the value \"777\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 484
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhonePrefixCode\" contains the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 485
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhoneSuffixCode\" contains the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 486
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_lteUs" +
                    "erEmail_TextBox\" contains the value \"testuser2@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 487
 testRunner.When("I click on the submit button labeled \"Submit User Profile Changes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 488
 testRunner.Then("the page title is \"E-Verify: Home Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("56 - Logout of E-Verify")]
        public virtual void _56_LogoutOfE_Verify()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("56 - Logout of E-Verify", ((string[])(null)));
#line 490
this.ScenarioSetup(scenarioInfo);
#line 491
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 492
 testRunner.When("I click on the button using element id \"anch_24\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 493
 testRunner.Then("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
