// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Features.Enrollment
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Employer Agent Web Services Enrollment")]
    public partial class EmployerAgentWebServicesEnrollmentFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EmployerAgentWebServicesEnrollment.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Employer Agent Web Services Enrollment", @"	1. Enroll web Services Employer Agent
	2. Employer Registration Page & Review (Scenarios 01-06) 
	3. Organization Designation, MOU Signatory, Company Informations, Agent Program Administrator Informations, Registration Review & Enroll (Scenarios 07-17)                                                                                                                                                                                                                                                                                                                                                                                                    
	4. Use WebHQ - search for agent to edit and validate company, set MOU activation date, save Program Administrator ID, Set Tutorial Complete/Temp Password for Program Admin (Scenarios 35-43)
	5. Login to everify as an Agent Program Administrator, Set New Password, Security Questions and Verify User Profile (Scenarios 44-46)
	6. Add a New Client, Organization Designation, Client Informations, Point of Contact(POC), Review & Register (Scenarios 47-56)
	7. Verify newly added client (Scenarios 57-58)
	8. Use WebHQ - search for client to edit and validate Client - Set Mou date for new client (Scenarios 59-60)
	9. Login to eVerify as an Agent Program Administrator and validate new client activation (Scenario 61)", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01-Navigate to E-Verify Registration Checklist page")]
        public virtual void _01_NavigateToE_VerifyRegistrationChecklistPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01-Navigate to E-Verify Registration Checklist page", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.Given("I navigate to the url for \"registration\" titled \"E-Verify – Employer Registration" +
                    " – Start Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.And("I click on the submit button labeled \"Continue\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Checklist\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02-Navigate to page E-Verify – Employer Registration – Start Here")]
        public virtual void _02_NavigateToPageE_VerifyEmployerRegistrationStartHere()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02-Navigate to page E-Verify – Employer Registration – Start Here", ((string[])(null)));
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
 testRunner.When("I click on the submit button labeled \"Begin E-Verify Enrollment\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Start Here\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03- Set Employer Access-Y Agent-Y Corporate-N Web Services-Y")]
        public virtual void _03_SetEmployerAccess_YAgent_YCorporate_NWebServices_Y()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03- Set Employer Access-Y Agent-Y Corporate-N Web Services-Y", ((string[])(null)));
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 25
 testRunner.When("I click on the radio button using element id \"radBpYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
 testRunner.And("I click on the radio button using element id \"radDaYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("I click on the radio button using element id \"radCorpNo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("I click on the radio button using element id \"radWsYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.Then("the page title is \"E-Verify - Employer Registration - Let’s Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04-Registration Review Page Verification")]
        public virtual void _04_RegistrationReviewPageVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04-Registration Review Page Verification", ((string[])(null)));
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 34
 testRunner.When("I access the table using tag \"div\" attribute type \"class\" attribute value \"box\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05-Review Page Verification Data")]
        [NUnit.Framework.TestCaseAttribute("2", "Yes", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "Yes", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4", "No", new string[0])]
        [NUnit.Framework.TestCaseAttribute("5", "Yes", new string[0])]
        public virtual void _05_ReviewPageVerificationData(string tableRowNumber, string data, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05-Review Page Verification Data", exampleTags);
#line 36
this.ScenarioSetup(scenarioInfo);
#line 37
 testRunner.Then(string.Format("table row number {0} contains the values {1} from the following table", tableRowNumber, data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06-Registration Review Page")]
        public virtual void _06_RegistrationReviewPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06-Registration Review Page", ((string[])(null)));
#line 46
this.ScenarioSetup(scenarioInfo);
#line 47
 testRunner.Given("the page title is \"E-Verify - Employer Registration - Let’s Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 48
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.Then("the page title is \"E-Verify - Employer Registration - Organization Designation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07-Set Organization Designation")]
        public virtual void _07_SetOrganizationDesignation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07-Set Organization Designation", ((string[])(null)));
#line 51
this.ScenarioSetup(scenarioInfo);
#line 52
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 53
 testRunner.When("I select the drop down text \"State Government\" using element id \"ucCategory_vscCa" +
                    "tegory_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Memorandum of Understanding" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08-Switch to iFrame to verify MOU")]
        public virtual void _08_SwitchToIFrameToVerifyMOU()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08-Switch to iFrame to verify MOU", ((string[])(null)));
#line 57
this.ScenarioSetup(scenarioInfo);
#line 58
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 59
 testRunner.When("I switch to iframe using element id \"ucRegistrationTerms_frmMou\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 60
 testRunner.Then("the page contains the text \"MEMORANDUM OF UNDERSTANDING\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 61
 testRunner.And("the page contains the text \"FOR WEB SERVICES E-VERIFY EMPLOYER AGENTS\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
 testRunner.And("I switch back to the body of the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("09-Memorandum of Understanding (MOU)")]
        public virtual void _09_MemorandumOfUnderstandingMOU()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09-Memorandum of Understanding (MOU)", ((string[])(null)));
#line 64
this.ScenarioSetup(scenarioInfo);
#line 65
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Memorandum of Understanding" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 66
 testRunner.When("I click on the radio button using element id \"ucRegistrationTerms_radAccept\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 67
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
 testRunner.Then("the page title is \"E-Verify – Employer Registration – MOU Signatory\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10-Add MOU Signatory")]
        public virtual void _10_AddMOUSignatory()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10-Add MOU Signatory", ((string[])(null)));
#line 70
this.ScenarioSetup(scenarioInfo);
#line 71
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 72
 testRunner.When("I set the text box using element id \"ucMouPoc_ltLastName_TextBox\" with the value " +
                    "\"Zahedt\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 73
 testRunner.And("I set the text box using element id \"ucMouPoc_ltFirstName_TextBox\" with the value" +
                    " \"John\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhoneAreaCode\" with the val" +
                    "ue \"202\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhonePrefixCode\" with the v" +
                    "alue \"123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhoneSuffixCode\" with the v" +
                    "alue \"9953\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.And("I set the text box using element id \"ucMouPoc_ltEmail_TextBox\" with the value \"au" +
                    "tomationtesting1988@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.And("I set the text box using element id \"ucMouPoc_ltEmail2_TextBox\" with the value \"a" +
                    "utomationtesting1988@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.And("I select the drop down text \"Yes\" using element id \"ucMouPoc_optAccess\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11- Enter Company Information")]
        public virtual void _11_EnterCompanyInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11- Enter Company Information", ((string[])(null)));
#line 83
this.ScenarioSetup(scenarioInfo);
#line 84
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 85
 testRunner.When("I set the text box using element id \"ucCompanyInfo_txtEmpName_TextBox\" with the v" +
                    "alue \"Variq Web Service\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 86
 testRunner.And("I set the text box using element id \"ucCompanyInfo_txtAddress1_TextBox\" with the " +
                    "value \"500 New Automation Drive\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
 testRunner.And("I set the text box using element id \"ucCompanyInfo_txtCity_TextBox\" with the valu" +
                    "e \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.And("I select the drop down text \"MARYLAND\" using element id \"ucCompanyInfo_vssState_S" +
                    "electorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 89
 testRunner.And("I set the text box using element id \"ucCompanyInfo_ltzZipCode_TextBox\" with the v" +
                    "alue \"20852\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.And("I select the drop down text \"MONTGOMERY\" using element id \"ucCompanyInfo_vscCount" +
                    "y_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 91
 testRunner.And("I set the text box using element id \"ucCompanyInfo_ltnEmployerId_TextBox\" with th" +
                    "e value \"128888888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 92
 testRunner.And("I select the drop down text \"1 to 4\" using element id \"ucCompanyInfo_vscNbrEmps_S" +
                    "electorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 93
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 94
 testRunner.Then("the page title is \"E-Verify – Employer Registration – NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("12-Generate NAIC Code")]
        public virtual void _12_GenerateNAICCode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12-Generate NAIC Code", ((string[])(null)));
#line 96
this.ScenarioSetup(scenarioInfo);
#line 97
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 98
 testRunner.When("I set the text box using element id \"ucNaics_ltNaicsCode_TextBox\" with the value " +
                    "\"221\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 99
 testRunner.And("I click on the submit button labeled \"Accept NAICS Code and Continue\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Hiring Sites\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("13-Hiring Sites Verification")]
        public virtual void _13_HiringSitesVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13-Hiring Sites Verification", ((string[])(null)));
#line 102
this.ScenarioSetup(scenarioInfo);
#line 103
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 104
 testRunner.Then("the selected drop down text using element id \"ucSites_rptHiringSites__ctl1_lstSta" +
                    "tes\" is \"MARYLAND\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 105
 testRunner.And("the text box using tag \"input\" attribute type \"value\" contains the value \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("14-Navigate to Program Admistrators")]
        public virtual void _14_NavigateToProgramAdmistrators()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14-Navigate to Program Admistrators", ((string[])(null)));
#line 107
this.ScenarioSetup(scenarioInfo);
#line 108
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Hiring Sites\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 109
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 110
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Program Administrators\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("15-Add a Second Program Administrators")]
        public virtual void _15_AddASecondProgramAdministrators()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("15-Add a Second Program Administrators", ((string[])(null)));
#line 112
this.ScenarioSetup(scenarioInfo);
#line 113
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 114
 testRunner.When("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltLastName_T" +
                    "extBox\" with the value \"Test-Smith\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 115
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltFirstName_" +
                    "TextBox\" with the value \"Frist-Name\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 116
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "eAreaCode\" with the value \"777\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 117
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "ePrefixCode\" with the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "eSuffixCode\" with the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 119
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltEmail_Text" +
                    "Box\" with the value \"testuser@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltEmail2_Tex" +
                    "tBox\" with the value \"testuser@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 121
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 122
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Registration Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("16-Registration Review-Verify Registration Details")]
        [NUnit.Framework.TestCaseAttribute("Variq Web Service", new string[0])]
        [NUnit.Framework.TestCaseAttribute("500 New Automation Drive", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Rockville", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MD", new string[0])]
        [NUnit.Framework.TestCaseAttribute("20852", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MONTGOMERY", new string[0])]
        [NUnit.Framework.TestCaseAttribute("128888888", new string[0])]
        [NUnit.Framework.TestCaseAttribute("1 to 4", new string[0])]
        [NUnit.Framework.TestCaseAttribute("State Government", new string[0])]
        [NUnit.Framework.TestCaseAttribute("221 - UTILITIES", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MARYLAND", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Test-Smith", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Frist-Name", new string[0])]
        [NUnit.Framework.TestCaseAttribute("(777) 888 - 9999", new string[0])]
        [NUnit.Framework.TestCaseAttribute("automationtesting1988@gmail.com", new string[0])]
        public virtual void _16_RegistrationReview_VerifyRegistrationDetails(string textOnPage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("16-Registration Review-Verify Registration Details", exampleTags);
#line 124
this.ScenarioSetup(scenarioInfo);
#line 125
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 126
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("17-Complete Enrollment to Register Agent")]
        public virtual void _17_CompleteEnrollmentToRegisterAgent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("17-Complete Enrollment to Register Agent", ((string[])(null)));
#line 146
this.ScenarioSetup(scenarioInfo);
#line 147
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Registration Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 148
 testRunner.When("I set the checkbox with element id \"ucSummary_chkAgree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 149
 testRunner.And("I click on the submit button labeled \"Register Employer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 150
 testRunner.Then("the page title is \"E-Verify – Employer Registration – You\'re Finished\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 151
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("18-Navigate to E-Verify Registration Checklist page")]
        public virtual void _18_NavigateToE_VerifyRegistrationChecklistPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("18-Navigate to E-Verify Registration Checklist page", ((string[])(null)));
#line 153
this.ScenarioSetup(scenarioInfo);
#line 154
 testRunner.Given("I navigate to the url for \"registration\" titled \"E-Verify – Employer Registration" +
                    " – Start Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 155
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 156
 testRunner.And("I click on the submit button labeled \"Continue\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 157
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Checklist\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("19-Navigate to page E-Verify – Employer Registration – Start Here")]
        public virtual void _19_NavigateToPageE_VerifyEmployerRegistrationStartHere()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("19-Navigate to page E-Verify – Employer Registration – Start Here", ((string[])(null)));
#line 159
this.ScenarioSetup(scenarioInfo);
#line 160
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 161
 testRunner.When("I click on the submit button labeled \"Begin E-Verify Enrollment\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 162
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Start Here\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("20- Set Employer Access-Y Agent-Y Corporate-N Web Services-Y")]
        public virtual void _20_SetEmployerAccess_YAgent_YCorporate_NWebServices_Y()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("20- Set Employer Access-Y Agent-Y Corporate-N Web Services-Y", ((string[])(null)));
#line 164
this.ScenarioSetup(scenarioInfo);
#line 165
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 166
 testRunner.When("I click on the radio button using element id \"radBpYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 167
 testRunner.And("I click on the radio button using element id \"radDaYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 168
 testRunner.And("I click on the radio button using element id \"radCorpNo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 169
 testRunner.And("I click on the radio button using element id \"radWsYes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 170
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 171
 testRunner.Then("the page title is \"E-Verify - Employer Registration - Let’s Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("21-Registration Review Page Verification")]
        public virtual void _21_RegistrationReviewPageVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("21-Registration Review Page Verification", ((string[])(null)));
#line 173
this.ScenarioSetup(scenarioInfo);
#line 174
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 175
 testRunner.When("I access the table using tag \"div\" attribute type \"class\" attribute value \"box\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("22-Review Page Verification Data")]
        [NUnit.Framework.TestCaseAttribute("2", "Yes", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "Yes", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4", "No", new string[0])]
        [NUnit.Framework.TestCaseAttribute("5", "Yes", new string[0])]
        public virtual void _22_ReviewPageVerificationData(string tableRowNumber, string data, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("22-Review Page Verification Data", exampleTags);
#line 177
this.ScenarioSetup(scenarioInfo);
#line 178
 testRunner.Then(string.Format("table row number {0} contains the values {1} from the following table", tableRowNumber, data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("23-Registration Review Page")]
        public virtual void _23_RegistrationReviewPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("23-Registration Review Page", ((string[])(null)));
#line 187
this.ScenarioSetup(scenarioInfo);
#line 188
 testRunner.Given("the page title is \"E-Verify - Employer Registration - Let’s Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 189
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 190
 testRunner.Then("the page title is \"E-Verify - Employer Registration - Organization Designation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("24-Set Organization Designation")]
        public virtual void _24_SetOrganizationDesignation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("24-Set Organization Designation", ((string[])(null)));
#line 192
this.ScenarioSetup(scenarioInfo);
#line 193
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 194
 testRunner.When("I select the drop down text \"State Government\" using element id \"ucCategory_vscCa" +
                    "tegory_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 195
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 196
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Memorandum of Understanding" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("25-Switch to iFrame to verify MOU")]
        public virtual void _25_SwitchToIFrameToVerifyMOU()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("25-Switch to iFrame to verify MOU", ((string[])(null)));
#line 198
this.ScenarioSetup(scenarioInfo);
#line 199
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 200
 testRunner.When("I switch to iframe using element id \"ucRegistrationTerms_frmMou\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 201
 testRunner.Then("the page contains the text \"MEMORANDUM OF UNDERSTANDING\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 202
 testRunner.And("the page contains the text \"FOR WEB SERVICES E-VERIFY EMPLOYER AGENTS\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 203
 testRunner.And("I switch back to the body of the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("26-Memorandum of Understanding (MOU)")]
        public virtual void _26_MemorandumOfUnderstandingMOU()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("26-Memorandum of Understanding (MOU)", ((string[])(null)));
#line 205
this.ScenarioSetup(scenarioInfo);
#line 206
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Memorandum of Understanding" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 207
 testRunner.When("I click on the radio button using element id \"ucRegistrationTerms_radAccept\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 208
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 209
 testRunner.Then("the page title is \"E-Verify – Employer Registration – MOU Signatory\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("27-Add MOU Signatory")]
        public virtual void _27_AddMOUSignatory()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("27-Add MOU Signatory", ((string[])(null)));
#line 211
this.ScenarioSetup(scenarioInfo);
#line 212
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 213
 testRunner.When("I set the text box using element id \"ucMouPoc_ltLastName_TextBox\" with the value " +
                    "\"Zahedt\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 214
 testRunner.And("I set the text box using element id \"ucMouPoc_ltFirstName_TextBox\" with the value" +
                    " \"John\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 215
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhoneAreaCode\" with the val" +
                    "ue \"202\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 216
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhonePrefixCode\" with the v" +
                    "alue \"123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 217
 testRunner.And("I set the text box using element id \"ucMouPoc_scPhone_PhoneSuffixCode\" with the v" +
                    "alue \"9953\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 218
 testRunner.And("I set the text box using element id \"ucMouPoc_ltEmail_TextBox\" with the value \"au" +
                    "tomationtesting1988@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 219
 testRunner.And("I set the text box using element id \"ucMouPoc_ltEmail2_TextBox\" with the value \"a" +
                    "utomationtesting1988@gmail.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 220
 testRunner.And("I select the drop down text \"Yes\" using element id \"ucMouPoc_optAccess\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 221
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 222
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("28- Enter Company Information")]
        public virtual void _28_EnterCompanyInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("28- Enter Company Information", ((string[])(null)));
#line 224
this.ScenarioSetup(scenarioInfo);
#line 225
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 226
 testRunner.When("I set the text box using element id \"ucCompanyInfo_txtEmpName_TextBox\" with the v" +
                    "alue \"Variq Web Service\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 227
 testRunner.And("I set the text box using element id \"ucCompanyInfo_txtAddress1_TextBox\" with the " +
                    "value \"500 New Automation Drive\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 228
 testRunner.And("I set the text box using element id \"ucCompanyInfo_txtCity_TextBox\" with the valu" +
                    "e \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 229
 testRunner.And("I select the drop down text \"MARYLAND\" using element id \"ucCompanyInfo_vssState_S" +
                    "electorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 230
 testRunner.And("I set the text box using element id \"ucCompanyInfo_ltzZipCode_TextBox\" with the v" +
                    "alue \"20852\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 231
 testRunner.And("I select the drop down text \"MONTGOMERY\" using element id \"ucCompanyInfo_vscCount" +
                    "y_SelectorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 232
 testRunner.And("I set the text box using element id \"ucCompanyInfo_ltnEmployerId_TextBox\" with th" +
                    "e value \"128888888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 233
 testRunner.And("I select the drop down text \"1 to 4\" using element id \"ucCompanyInfo_vscNbrEmps_S" +
                    "electorDrop\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 234
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 235
 testRunner.Then("the page title is \"E-Verify – Employer Registration – NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("29-Generate NAIC Code")]
        public virtual void _29_GenerateNAICCode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("29-Generate NAIC Code", ((string[])(null)));
#line 237
this.ScenarioSetup(scenarioInfo);
#line 238
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 239
 testRunner.When("I set the text box using element id \"ucNaics_ltNaicsCode_TextBox\" with the value " +
                    "\"221\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 240
 testRunner.And("I click on the submit button labeled \"Accept NAICS Code and Continue\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 241
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Hiring Sites\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("30-Hiring Sites Verification")]
        public virtual void _30_HiringSitesVerification()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("30-Hiring Sites Verification", ((string[])(null)));
#line 243
this.ScenarioSetup(scenarioInfo);
#line 244
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 245
 testRunner.Then("the selected drop down text using element id \"ucSites_rptHiringSites__ctl1_lstSta" +
                    "tes\" is \"MARYLAND\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 246
 testRunner.And("the text box using tag \"input\" attribute type \"value\" contains the value \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("31-Navigate to Program Admistrators")]
        public virtual void _31_NavigateToProgramAdmistrators()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("31-Navigate to Program Admistrators", ((string[])(null)));
#line 248
this.ScenarioSetup(scenarioInfo);
#line 249
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Hiring Sites\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 250
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 251
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Program Administrators\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("32-Add a Second Program Administrators")]
        public virtual void _32_AddASecondProgramAdministrators()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("32-Add a Second Program Administrators", ((string[])(null)));
#line 253
this.ScenarioSetup(scenarioInfo);
#line 254
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 255
 testRunner.When("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltLastName_T" +
                    "extBox\" with the value \"Test-Smith\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 256
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltFirstName_" +
                    "TextBox\" with the value \"Frist-Name\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 257
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "eAreaCode\" with the value \"777\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 258
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "ePrefixCode\" with the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 259
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_scPhone_Phon" +
                    "eSuffixCode\" with the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 260
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltEmail_Text" +
                    "Box\" with the value \"testuser@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 261
 testRunner.And("I set the text box using element id \"ucRegContacts_rptContacts__ctl0_ltEmail2_Tex" +
                    "tBox\" with the value \"testuser@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 262
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 263
 testRunner.Then("the page title is \"E-Verify – Employer Registration – Registration Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("33-Registration Review-Verify Registration Details")]
        [NUnit.Framework.TestCaseAttribute("Variq Web Service", new string[0])]
        [NUnit.Framework.TestCaseAttribute("500 New Automation Drive", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Rockville", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MD", new string[0])]
        [NUnit.Framework.TestCaseAttribute("20852", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MONTGOMERY", new string[0])]
        [NUnit.Framework.TestCaseAttribute("128888888", new string[0])]
        [NUnit.Framework.TestCaseAttribute("1 to 4", new string[0])]
        [NUnit.Framework.TestCaseAttribute("State Government", new string[0])]
        [NUnit.Framework.TestCaseAttribute("221 - UTILITIES", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MARYLAND", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Test-Smith", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Frist-Name", new string[0])]
        [NUnit.Framework.TestCaseAttribute("(777) 888 - 9999", new string[0])]
        [NUnit.Framework.TestCaseAttribute("automationtesting1988@gmail.com", new string[0])]
        public virtual void _33_RegistrationReview_VerifyRegistrationDetails(string textOnPage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("33-Registration Review-Verify Registration Details", exampleTags);
#line 265
this.ScenarioSetup(scenarioInfo);
#line 266
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 267
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("34-Complete Enrollment to Register Agent")]
        public virtual void _34_CompleteEnrollmentToRegisterAgent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("34-Complete Enrollment to Register Agent", ((string[])(null)));
#line 287
this.ScenarioSetup(scenarioInfo);
#line 288
 testRunner.Given("the page title is \"E-Verify – Employer Registration – Registration Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 289
 testRunner.When("I set the checkbox with element id \"ucSummary_chkAgree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 290
 testRunner.And("I click on the submit button labeled \"Register Employer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 291
 testRunner.Then("the page title is \"E-Verify – Employer Registration – You\'re Finished\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 292
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("35-Logon to WebHQ")]
        public virtual void _35_LogonToWebHQ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("35-Logon to WebHQ", ((string[])(null)));
#line 294
this.ScenarioSetup(scenarioInfo);
#line 295
 testRunner.Given("I navigate to the url for \"webhq\" titled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 296
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 297
 testRunner.And("I click on the button using element id \"btnContinue1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 298
 testRunner.And("I set the text box using element id \"txtUserID\" with the value for \"webhq-usernam" +
                    "e\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 299
 testRunner.And("I set the text box using element id \"txtUserPassword\" with the value for \"webhq-p" +
                    "assword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 300
 testRunner.And("I click on the submit button labeled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 301
 testRunner.Then("the page title is \"Web-HQ: Home\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("36-Search Company")]
        public virtual void _36_SearchCompany()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("36-Search Company", ((string[])(null)));
#line 303
this.ScenarioSetup(scenarioInfo);
#line 304
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 305
 testRunner.When("I click on the link containing the text \"Maintain Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 306
 testRunner.And("the page title is \"Company Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 307
 testRunner.And("I set the text box using element id \"txtEmployer_TextBox\" with the value \"Variq W" +
                    "eb Service\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 308
 testRunner.And("I click on the submit button labeled \"Display Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 309
 testRunner.Then("the page title is \"Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("37-Navigate to company details")]
        public virtual void _37_NavigateToCompanyDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("37-Navigate to company details", ((string[])(null)));
#line 311
this.ScenarioSetup(scenarioInfo);
#line 312
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 313
 testRunner.When("I access the table using tag \"table\" attribute type \"class\" attribute value \"Cont" +
                    "rolText\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 314
 testRunner.And("I save the table row number containing the data \"PENDING\" in column number \"11\" i" +
                    "nto the variable \"tableRowNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 315
 testRunner.And("I click on the button labeled \"Edit\" in the table row number saved in the variabl" +
                    "e \"tableRowNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 316
 testRunner.Then("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("38-Validate and Match Company")]
        public virtual void _38_ValidateAndMatchCompany()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("38-Validate and Match Company", ((string[])(null)));
#line 318
this.ScenarioSetup(scenarioInfo);
#line 319
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 320
 testRunner.When("I click on the submit button labeled \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 321
 testRunner.And("the page title is \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 322
 testRunner.And("I skip scenario if element is missing using tag \"input\" attribute type \"value\" at" +
                    "tribute value \"Confirm Company Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 323
 testRunner.And("I click on the submit button labeled \"Confirm Company Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 324
 testRunner.And("I select the drop down text \"Match\" using element id \"vscMatchStatus_SelectorDrop" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 325
 testRunner.And("I click on the submit button labeled \"Confirm Validity\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 326
 testRunner.And("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 327
 testRunner.And("I click on the submit button labeled \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 328
 testRunner.And("I access table number \"2\" using tag \"table\" attribute type \"id\" attribute value \"" +
                    "structure\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 329
 testRunner.Then("table row number \"1\" column number \"2\" contains the value \"Match\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("39-Company Details page")]
        public virtual void _39_CompanyDetailsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("39-Company Details page", ((string[])(null)));
#line 331
this.ScenarioSetup(scenarioInfo);
#line 332
 testRunner.Given("the page title is \"IIP Match Review\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 333
 testRunner.When("I click on the submit button labeled \"Return to Maintain Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 334
 testRunner.And("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 335
 testRunner.And("I access table number \"6\" using tag \"table\" attribute type \"id\" attribute value \"" +
                    "structure\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 336
 testRunner.And("I click on the button labeled \"View / Edit\" in row number \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 337
 testRunner.Then("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("40-Verify the Access Method")]
        [NUnit.Framework.TestCaseAttribute("WEB-DABP", new string[0])]
        [NUnit.Framework.TestCaseAttribute("WS-EMP", new string[0])]
        public virtual void _40_VerifyTheAccessMethod(string textOnPage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("40-Verify the Access Method", exampleTags);
#line 339
this.ScenarioSetup(scenarioInfo);
#line 340
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 341
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("41-Set MOU Signed Date to Activate User")]
        public virtual void _41_SetMOUSignedDateToActivateUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41-Set MOU Signed Date to Activate User", ((string[])(null)));
#line 348
this.ScenarioSetup(scenarioInfo);
#line 349
      testRunner.Given("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 350
   testRunner.When("I set the text box using element id \"ucCompanyAccess_cdtMOUDate_dateTextBox\" with" +
                    " the value \"01/02/2016\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 351
   testRunner.And("I click on the submit button labeled \"Submit Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 352
      testRunner.And("I access table number \"4\" using tag \"table\" attribute type \"id\" attribute value \"" +
                    "tblAddress\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 353
   testRunner.Then("table row number \"10\" column number \"2\" contains the value \"Total Active Users:\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 354
   testRunner.And("table row number \"10\" column number \"3\" contains the value \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("42-Edit Active User and Save User ID")]
        public virtual void _42_EditActiveUserAndSaveUserID()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("42-Edit Active User and Save User ID", ((string[])(null)));
#line 356
this.ScenarioSetup(scenarioInfo);
#line 357
 testRunner.Given("the page title is \"Company Details\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 358
 testRunner.When("I click on the button labeled \"View / Edit\" in row number \"10\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 359
 testRunner.And("the page title is \"Employer User Summary\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 360
 testRunner.And("I access the table using element id \"dgCpsUsers\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 361
 testRunner.And("I save the data from table row number \"3\" column number \"2\" into the variable \"us" +
                    "erid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 362
 testRunner.And("I click on table row number \"3\" in column number \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 363
 testRunner.Then("the page title is \"User Details - View / Modify User Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("43-Edit User, Set Tutorial Complete and Set Temp Password")]
        public virtual void _43_EditUserSetTutorialCompleteAndSetTempPassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("43-Edit User, Set Tutorial Complete and Set Temp Password", ((string[])(null)));
#line 365
this.ScenarioSetup(scenarioInfo);
#line 366
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 367
 testRunner.When("I set the checkbox with element id \"ucCpsUserModEmployer_chkTutorialComplete\" to " +
                    "\"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 368
 testRunner.And("I set the text box using element id \"ucCpsUserModEmployer_ltbNewPwd_TextBox\" with" +
                    " the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 369
 testRunner.And("I set the text box using element id \"ucCpsUserModEmployer_ltbConfPwd_TextBox\" wit" +
                    "h the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 370
 testRunner.And("I click on the submit button labeled \"Submit User Modifications\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 371
 testRunner.Then("the page title is \"User Details - User Confirmation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("44-Logon to eVerify for creating new clients")]
        public virtual void _44_LogonToEVerifyForCreatingNewClients()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("44-Logon to eVerify for creating new clients", ((string[])(null)));
#line 373
this.ScenarioSetup(scenarioInfo);
#line 374
 testRunner.Given("I navigate to the url for \"everify\" titled \"E-Verify: Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 375
 testRunner.When("I click on the submit button containing the text \"I agree\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 376
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_UserIdTextBox_TextBox" +
                    "\" with the value stored in the variable \"userid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 377
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_PasswordTextBox_TextB" +
                    "ox\" with the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 378
 testRunner.And("I click on the submit button labeled \"Log In\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 379
 testRunner.Then("the page title is \"E-Verify: Change Password\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("45-Submit New Password and Security Questions")]
        public virtual void _45_SubmitNewPasswordAndSecurityQuestions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("45-Submit New Password and Security Questions", ((string[])(null)));
#line 381
this.ScenarioSetup(scenarioInfo);
#line 382
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 383
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_ltbOldPwd_TextBox\" wi" +
                    "th the value \"Welcome1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 384
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ltbNewPwd_TextBox\" wi" +
                    "th the value \"Password1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 385
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ltbValidatePwd_TextBo" +
                    "x\" with the value \"Password1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 386
 testRunner.And("I select the drop down text \"What is the name of the first school you attended?\" " +
                    "using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 387
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer1_TextBox\" with the value \"abcde\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 388
 testRunner.And("I select the drop down text \"What is the name of your first pet?\" using element i" +
                    "d \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 389
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer2_TextBox\" with the value \"test\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 390
 testRunner.And("I select the drop down text \"What is your father\'s middle name?\" using element id" +
                    " \"MainContentPlaceHolder_ucPwdChallengeAnswers_lstQuestion3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 391
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucPwdChallengeAnswers" +
                    "_txtAnswer3_TextBox\" with the value \"name\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 392
 testRunner.And("I click on the submit button labeled \"Submit\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 393
 testRunner.Then("the page title is \"E-Verify: Update User Profile\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("46-Verify User Profile and logon to eVerify")]
        public virtual void _46_VerifyUserProfileAndLogonToEVerify()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("46-Verify User Profile and logon to eVerify", ((string[])(null)));
#line 395
this.ScenarioSetup(scenarioInfo);
#line 396
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 397
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhoneAreaCode\" contains the value \"777\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 398
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhonePrefixCode\" contains the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 399
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_ptbPh" +
                    "oneNumber_PhoneSuffixCode\" contains the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 400
 testRunner.Then("the text box using element id \"MainContentPlaceHolder_ucEvProfileInfoUpdate_lteUs" +
                    "erEmail_TextBox\" contains the value \"testuser@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 401
 testRunner.When("I click on the submit button labeled \"Submit User Profile Changes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 402
 testRunner.Then("the page title is \"E-Verify: Home Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("47-Navigate to Clients > Add New Client")]
        public virtual void _47_NavigateToClientsAddNewClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("47-Navigate to Clients > Add New Client", ((string[])(null)));
#line 404
this.ScenarioSetup(scenarioInfo);
#line 405
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 406
 testRunner.When("I click on the link using element id \"anch_7\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 407
 testRunner.And("I click on the link using element id \"anch_8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 408
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Organization Designation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("48- Set Organization Designation")]
        public virtual void _48_SetOrganizationDesignation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("48- Set Organization Designation", ((string[])(null)));
#line 410
this.ScenarioSetup(scenarioInfo);
#line 411
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 412
 testRunner.When("I select the drop down text \"Local Government\" using element id \"MainContentPlace" +
                    "Holder_ClientCategory1_ddlCategory\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 413
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 414
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("49-Add Client Information")]
        public virtual void _49_AddClientInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("49-Add Client Information", ((string[])(null)));
#line 416
this.ScenarioSetup(scenarioInfo);
#line 417
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 418
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_t" +
                    "xtEmpName_TextBox\" with the value \"One Test Client\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 419
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_t" +
                    "xtAddress1_TextBox\" with the value \"123 Client Dr\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 420
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_t" +
                    "xtCity_TextBox\" with the value \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 421
 testRunner.And("I select the drop down text \"MARYLAND\" using element id \"MainContentPlaceHolder_C" +
                    "ompanyInformation1_ddlState\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 422
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_l" +
                    "tzZipCode_TextBox\" with the value \"00000\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 423
 testRunner.And("I select the drop down text \"MONTGOMERY\" using element id \"MainContentPlaceHolder" +
                    "_CompanyInformation1_ddlCounty\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 424
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_CompanyInformation1_l" +
                    "tnEmployerId_TextBox\" with the value \"888888889\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 425
 testRunner.And("I select the drop down text \"100 to 499\" using element id \"MainContentPlaceHolder" +
                    "_CompanyInformation1_ddlTotalEmployeeRange\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 426
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 427
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Enter NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("50-Add NAIC Code for New Client")]
        public virtual void _50_AddNAICCodeForNewClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("50-Add NAIC Code for New Client", ((string[])(null)));
#line 429
this.ScenarioSetup(scenarioInfo);
#line 430
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 431
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_Naics_ltNaicsCode_Tex" +
                    "tBox\" with the value \"722\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 432
 testRunner.And("I click on the submit button labeled \"Accept NAICS Code\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 433
 testRunner.Then("the page title is \"E-Verify: Client Wizard - How Many Hiring Sites?\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("51-Hiring Sites")]
        public virtual void _51_HiringSites()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("51-Hiring Sites", ((string[])(null)));
#line 435
this.ScenarioSetup(scenarioInfo);
#line 436
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 437
 testRunner.When("I click on the submit button labeled \"Single Site Verification\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 438
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Enter Program Administrator\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("52-Enter Program Administrator information")]
        public virtual void _52_EnterProgramAdministratorInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("52-Enter Program Administrator information", ((string[])(null)));
#line 440
this.ScenarioSetup(scenarioInfo);
#line 441
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 442
 testRunner.When("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ltaLastNam" +
                    "e_TextBox\" with the value \"Test Client-LN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 443
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ltaFirstNa" +
                    "me_TextBox\" with the value \"Test Client-FN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 444
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ptbPhoneNu" +
                    "mber_PhoneAreaCode\" with the value \"301\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 445
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ptbPhoneNu" +
                    "mber_PhonePrefixCode\" with the value \"888\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 446
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_ptbPhoneNu" +
                    "mber_PhoneSuffixCode\" with the value \"9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 447
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_ucContacts_lteEmailAd" +
                    "dress_TextBox\" with the value \"clientemail@variq.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 448
 testRunner.And("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 449
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Points of Contact Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("53-Verify POC Summary")]
        public virtual void _53_VerifyPOCSummary()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("53-Verify POC Summary", ((string[])(null)));
#line 451
this.ScenarioSetup(scenarioInfo);
#line 452
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 453
 testRunner.When("I access the table using element id \"MainContentPlaceHolder_ucContacts_ContactsGr" +
                    "id\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 454
 testRunner.Then("table row number \"3\" column number \"1\" contains the value \"Test Client-LN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 455
 testRunner.And("table row number \"3\" column number \"2\" contains the value \"Test Client-FN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 456
 testRunner.And("table row number \"3\" column number \"4\" contains the value \"(301) 888 - 9999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 457
 testRunner.And("table row number \"3\" column number \"6\" contains the value \"clientemail@variq.com\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("54-Navigate to Company Information")]
        public virtual void _54_NavigateToCompanyInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("54-Navigate to Company Information", ((string[])(null)));
#line 459
this.ScenarioSetup(scenarioInfo);
#line 460
 testRunner.Given("the page title is \"E-Verify: Client Wizard - Points of Contact Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 461
 testRunner.When("I click on the submit button labeled \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 462
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("55-Verify Company Information")]
        [NUnit.Framework.TestCaseAttribute("One Test Client", new string[0])]
        [NUnit.Framework.TestCaseAttribute("123 Client Dr", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Rockville", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MD", new string[0])]
        [NUnit.Framework.TestCaseAttribute("00000", new string[0])]
        [NUnit.Framework.TestCaseAttribute("MONTGOMERY", new string[0])]
        [NUnit.Framework.TestCaseAttribute("888888889", new string[0])]
        [NUnit.Framework.TestCaseAttribute("100 to 499", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Local Government", new string[0])]
        [NUnit.Framework.TestCaseAttribute("722 - FOOD SERVICES AND DRINKING PLACES (722)", new string[0])]
        public virtual void _55_VerifyCompanyInformation(string textOnPage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("55-Verify Company Information", exampleTags);
#line 464
this.ScenarioSetup(scenarioInfo);
#line 465
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 466
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("56-Register Client")]
        public virtual void _56_RegisterClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("56-Register Client", ((string[])(null)));
#line 481
this.ScenarioSetup(scenarioInfo);
#line 482
 testRunner.Given("the page title is \"E-Verify: Client Wizard - Company Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 483
 testRunner.When("I click on the submit button labeled \"Register Client\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 484
 testRunner.Then("the page title is \"E-Verify: Client Wizard - Thank you for registering for E-Veri" +
                    "fy\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("57-Navigate to Newly Registered Client")]
        public virtual void _57_NavigateToNewlyRegisteredClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("57-Navigate to Newly Registered Client", ((string[])(null)));
#line 486
this.ScenarioSetup(scenarioInfo);
#line 487
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 488
 testRunner.When("I click on the link using element id \"anch_7\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 489
 testRunner.And("I click on the link using element id \"anch_9\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 490
 testRunner.And("I click on the submit button labeled \"Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 491
 testRunner.Then("the page title is \"E-Verify: Search Results\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("58- Verify newly created RWD Client")]
        [NUnit.Framework.TestCaseAttribute("3", "One Test Client", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "123 Client Dr", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "Rockville", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "MD", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "PENDING", new string[0])]
        public virtual void _58_VerifyNewlyCreatedRWDClient(string tableRowNumber, string data, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("58- Verify newly created RWD Client", exampleTags);
#line 493
this.ScenarioSetup(scenarioInfo);
#line 494
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 495
 testRunner.When("I access the table using element id \"MainContentPlaceHolder_ClientCompanyGrid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 496
 testRunner.Then(string.Format("table row number {0} contains the values {1} from the following table", tableRowNumber, data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("59-Logon to WebHQ and search for new client")]
        public virtual void _59_LogonToWebHQAndSearchForNewClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("59-Logon to WebHQ and search for new client", ((string[])(null)));
#line 506
this.ScenarioSetup(scenarioInfo);
#line 507
 testRunner.Given("I navigate to the url for \"webhq\" titled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 508
 testRunner.When("I set the checkbox with element id \"cb_Iagree\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 509
 testRunner.And("I click on the button using element id \"btnContinue1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 510
 testRunner.And("I set the text box using element id \"txtUserID\" with the value for \"webhq-usernam" +
                    "e\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 511
 testRunner.And("I set the text box using element id \"txtUserPassword\" with the value for \"webhq-p" +
                    "assword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 512
 testRunner.And("I click on the submit button labeled \"Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 513
 testRunner.And("the page title is \"Web-HQ: Home\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 514
 testRunner.And("I click on the link containing the text \"Maintain Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 515
 testRunner.And("the page title is \"Company Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 516
 testRunner.And("I set the text box using element id \"txtEmployer_TextBox\" with the value \"One Tes" +
                    "t Client\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 517
 testRunner.And("I click on the submit button labeled \"Display Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 518
 testRunner.Then("the page title is \"Company Summary List\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("60-Set MOU date for new client")]
        public virtual void _60_SetMOUDateForNewClient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("60-Set MOU date for new client", ((string[])(null)));
#line 520
this.ScenarioSetup(scenarioInfo);
#line 521
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 522
 testRunner.When("I access the table using tag \"table\" attribute type \"class\" attribute value \"Cont" +
                    "rolText\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 523
 testRunner.And("I save the table row number containing the data \"PENDING\" in column number \"11\" i" +
                    "nto the variable \"tableRowNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 524
 testRunner.And("I click on the button labeled \"Edit\" in the table row number saved in the variabl" +
                    "e \"tableRowNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 525
 testRunner.And("the page title is \"Client Company\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 526
 testRunner.And("I access table number \"5\" using tag \"table\" attribute type \"id\" attribute value \"" +
                    "tblAddress\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 527
 testRunner.And("I click on the button labeled \"View / Edit\" in row number \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 528
 testRunner.And("I set the text box using element id \"ucCompanyAccess_cdtMOUDate_dateTextBox\" with" +
                    " the value \"01/03/2016\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 529
 testRunner.And("I click on the submit button labeled \"Submit Information\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 530
 testRunner.Then("table row number \"2\" column number \"3\" contains the value \"01/03/2016\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("61-Finally logon to eVerify and validate new client activation")]
        public virtual void _61_FinallyLogonToEVerifyAndValidateNewClientActivation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("61-Finally logon to eVerify and validate new client activation", ((string[])(null)));
#line 532
this.ScenarioSetup(scenarioInfo);
#line 533
 testRunner.Given("I navigate to the url for \"everify\" titled \"E-Verify: Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 534
 testRunner.When("I click on the submit button containing the text \"I agree\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 535
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_UserIdTextBox_TextBox" +
                    "\" with the value stored in the variable \"userid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 536
 testRunner.And("I set the text box using element id \"MainContentPlaceHolder_PasswordTextBox_TextB" +
                    "ox\" with the value \"Password1!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 537
    testRunner.And("I click on the submit button labeled \"Log In\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 538
 testRunner.And("I click on the link using element id \"anch_7\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 539
 testRunner.And("I click on the link using element id \"anch_9\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 540
 testRunner.And("I click on the submit button labeled \"Search\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 541
 testRunner.And("I access the table using element id \"MainContentPlaceHolder_ClientCompanyGrid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 542
 testRunner.Then("table row number \"3\" column number \"6\" contains the value \"ACTIVE\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 543
 testRunner.And("table row number \"3\" column number \"2\" contains the value \"One Test Client\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 544
 testRunner.And("I click on the link containing the text \"LOG OUT\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 545
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
