// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Features.ShoppingCart
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Online Shopping Cart")]
    public partial class OnlineShoppingCartFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "OnlineShoppingCart.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Online Shopping Cart", "\t1. Register New User with Email Address\r\n\t\ta. Navigate to the Online Shopping Ca" +
                    "rt (OSC) and verify login page\r\n\t\tb. Register using Email Address\r\n\t\t\t- Click on" +
                    " Registration link\r\n\t\t\t- First & Last Name \r\n\t\t\t- Email Address\r\n\t\t\t- Password: " +
                    "8 Chars, 1 special, 1 number\r\n\t\t\t- Address: Line 1 & 2, City, State, Zip\r\n\t\t\t- C" +
                    "C: 16 digits, 2 digit Mon & Yr, 3 digit Security Code\r\n\t\t\t- 5 Security Q, atleas" +
                    "t 1 question to be filled\r\n\t\tc. Submit Registration & verify Product Catalog hom" +
                    "e page \r\n\t\td. logout\r\n\r\n\t2. Register using Duplicate Email\r\n\t\ta. Navigate to OSC" +
                    "\r\n\t\tb. Use same Email Address and other info to register\r\n\t\tc. Verify error mess" +
                    "age - Duplicate Email Address used\r\n\r\n\t3. Register New User with User ID\r\n\t\ta. N" +
                    "avigate to OSC\r\n\t\tb. Register using User Id\r\n\t\tc. Verify home page & logout\r\n\r\n\t" +
                    "4. Register using Duplicate User ID\r\n\t\ta. Navigate to OSC\r\n\t\tb. Use same User ID" +
                    " and other info to register\r\n\t\tc. Verify error message - Duplicate User ID used\r" +
                    "\n\r\n\t5. Login Validation\r\n\t\ta. No User ID & No Password, \r\n\t\tb. Invalid User ID &" +
                    " Password\r\n\t\tc. Valid User ID & Invalid password\r\n\t\td. Invalid User ID & Valid P" +
                    "assword\r\n\t\te. Correct User ID & Password should now work\r\n\r\n\t6. Product Catalog " +
                    "home page - Verify Item Name & Price\r\n\t\ta. We\'re already logged in\r\n\t\tb. Verify " +
                    "10 catalog items\r\n\t\tc. Verify image for each item/product\r\n\t\td. Verify Price is " +
                    "displayed\r\n\r\n\t7. Product Catalog Page - Select items and click on Shopping Cart\r" +
                    "\n\t\ta. Add a number for a few items\r\n\t\tb. Remove item count for one of the select" +
                    "ed items\r\n\t\tc. Click on Shopping Cart \r\n\t\t\r\n\t8. Shopping Cart Page\r\n\t\ta. Validat" +
                    "e selected items, quantities, and total cost\r\n\t\tb. Remove item count for one ite" +
                    "m and change the quantity for another item\r\n\t\tc. Update Shopping Cart and verify" +
                    " updates (0 quantity item is removed and quantity updated for the other)\r\n\t\t\r\n\t9" +
                    ". From Shopping Cart, go to Product Catalog Page\r\n\t\ta. Click on \'Continue Shoppi" +
                    "ng\' and verify Product Catalog Vpage\r\n\t\tb. Verify selected items and count based" +
                    " on updates made in previous scenario\r\n\t\tc. Select 2 additional items, remove 1 " +
                    "item already selected\r\n\t\td. Click on Shopping Cart \r\n\r\n\t10. Shopping Cart Page -" +
                    " Verify final details of product selections\r\n\t\ta. Validate final selection of it" +
                    "ems, quantities, and total cost\r\n\r\n\t11. Go to Checkout\r\n\t\ta. Click on Checkout b" +
                    "utton\r\n\t\tb. Verify Review Order page display\r\n\r\n\t12. Review Order Page \r\n\t\ta. Ve" +
                    "rify selected items, count, and total cost\r\n\t\tb. Verify CC info\r\n\t\tc. Verify Shi" +
                    "pping Address (entered during Registration)\r\n\t\td. Enter a new Shipping Address\r\n" +
                    "\r\n\t13. Click on Submit Order and verify Confirmation Page\r\n\t\ta. Click on Submit " +
                    "Order \r\n\t\tb. Verify contents\r\n\t\tc. Log out\r\n\r\n\t14. When not logged in, navigatin" +
                    "g to any of the OSC URLs will redirect to Login Page\r\n\t\ta. Without loggin in, na" +
                    "vigate to any of the OSC URLs\r\n\t\tb. Verify Login page is displayed", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("001-Register new user with Email Address")]
        public virtual void _001_RegisterNewUserWithEmailAddress()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("001-Register new user with Email Address", ((string[])(null)));
#line 82
this.ScenarioSetup(scenarioInfo);
#line 83
 testRunner.Given("I navigate to the url \"http://54.174.90.169:8080\" titled \"ShoppingDemo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 84
 testRunner.When("I click on the link containing the text \"Sign up\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 85
 testRunner.And("I set the text box using element id \"user_login_id\" with the value \"sheridan\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
 testRunner.And("I set the text box using element id \"user_email\" with the value \"sheridan_durgan@" +
                    "putsbox.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
 testRunner.And("I set the text box using element id \"user_first_name\" with the value \"sheridan\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.And("I set the text box using element id \"user_last_name\" with the value \"durgan\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 89
 testRunner.And("I set the text box using element id \"user_street_address\" with the value \"2600 To" +
                    "wer Oaks Blvd\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.And("I set the text box using element id \"user_city\" with the value \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 91
 testRunner.And("I set the text box using element id \"user_state\" with the value \"Maryland\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 92
 testRunner.And("I set the text box using element id \"user_zip\" with the value \"20876\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 93
 testRunner.And("I set the text box using element id \"user_cc_number\" with the value \"546680922300" +
                    "1601\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 94
 testRunner.And("I set the text box using element id \"user_cvv\" with the value \"999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 95
 testRunner.And("I set the text box using element id \"user_cc_exp_date\" with the value \"01/2020\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 96
 testRunner.And("I set the text box using element id \"user_password\" with the value \"Autotest123!\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 97
 testRunner.And("I set the text box using element id \"user_password_confirmation\" with the value \"" +
                    "Autotest123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
 testRunner.And("I set the text box using element id \"user_security_answer\" with the value \"circul" +
                    "ar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
 testRunner.And("I click on the submit button labeled \"Sign up\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 101
 testRunner.Then("the page contains the text \"Catalog\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("002-Login with valid credentials")]
        public virtual void _002_LoginWithValidCredentials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("002-Login with valid credentials", ((string[])(null)));
#line 103
this.ScenarioSetup(scenarioInfo);
#line 104
 testRunner.Given("I navigate to the url \"http://54.174.90.169:8080\" titled \"ShoppingDemo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 105
 testRunner.When("I set the text box using element id \"login_email_field\" with the value \"clara@put" +
                    "sbox.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 106
 testRunner.And("I set the text box using element id \"login_password_field\" with the value \"Autote" +
                    "st123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 107
 testRunner.And("I click on the button using element id \"login_submit_button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
 testRunner.Then("the page title is \"ShoppingDemo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 109
 testRunner.And("the page contains the text \"Catalog\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("003-Logout")]
        public virtual void _003_Logout()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("003-Logout", ((string[])(null)));
#line 111
this.ScenarioSetup(scenarioInfo);
#line 112
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 113
 testRunner.When("I click on the link containing the text \"Logout\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 114
 testRunner.Then("the page contains the text \"You need to sign in or sign up before continuing.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("004- Login Validation - Empty User ID & Password")]
        public virtual void _004_LoginValidation_EmptyUserIDPassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("004- Login Validation - Empty User ID & Password", ((string[])(null)));
#line 116
this.ScenarioSetup(scenarioInfo);
#line 117
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 118
 testRunner.When("I set the text box using element id \"login_email_field\" with the value \" \"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 119
 testRunner.And("I set the text box using element id \"login_password_field\" with the value \" \"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
 testRunner.And("I click on the button using element id \"login_submit_button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 121
 testRunner.Then("the page contains the text \"Invalid Email or password.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("005- Login Validation - Invalid User ID & Invalid Password")]
        public virtual void _005_LoginValidation_InvalidUserIDInvalidPassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("005- Login Validation - Invalid User ID & Invalid Password", ((string[])(null)));
#line 123
this.ScenarioSetup(scenarioInfo);
#line 124
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 125
 testRunner.When("I set the text box using element id \"login_email_field\" with the value \"invalidUs" +
                    "erId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 126
 testRunner.And("I set the text box using element id \"login_password_field\" with the value \"invali" +
                    "dPassword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 127
 testRunner.And("I click on the button using element id \"login_submit_button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 128
 testRunner.Then("the page contains the text \"Invalid Email or password.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("006- Login Validation - Valid User ID & Invalid Password")]
        public virtual void _006_LoginValidation_ValidUserIDInvalidPassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("006- Login Validation - Valid User ID & Invalid Password", ((string[])(null)));
#line 130
this.ScenarioSetup(scenarioInfo);
#line 131
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 132
 testRunner.When("I set the text box using element id \"login_email_field\" with the value \"clara@put" +
                    "sbox.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 133
 testRunner.And("I set the text box using element id \"login_password_field\" with the value \"invali" +
                    "dPassword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 134
 testRunner.And("I click on the button using element id \"login_submit_button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 135
 testRunner.Then("the page contains the text \"Invalid Email or password.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("007- Login Validation - Invalid User ID & Valid Password")]
        public virtual void _007_LoginValidation_InvalidUserIDValidPassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("007- Login Validation - Invalid User ID & Valid Password", ((string[])(null)));
#line 137
this.ScenarioSetup(scenarioInfo);
#line 138
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 139
 testRunner.When("I set the text box using element id \"login_email_field\" with the value \"invalidUs" +
                    "erId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 140
 testRunner.And("I set the text box using element id \"login_password_field\" with the value \"Autote" +
                    "st123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 141
 testRunner.And("I click on the button using element id \"login_submit_button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
 testRunner.Then("the page contains the text \"Invalid Email or password.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("008- Succesful Login - Valid User ID & Password")]
        public virtual void _008_SuccesfulLogin_ValidUserIDPassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("008- Succesful Login - Valid User ID & Password", ((string[])(null)));
#line 144
this.ScenarioSetup(scenarioInfo);
#line 145
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 146
 testRunner.When("I set the text box using element id \"login_email_field\" with the value \"clara@put" +
                    "sbox.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 147
 testRunner.And("I set the text box using element id \"login_password_field\" with the value \"Autote" +
                    "st123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 148
 testRunner.And("I click on the button using element id \"login_submit_button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 149
 testRunner.Then("the page title is \"ShoppingDemo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 150
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02- Duplicate Email Address")]
        public virtual void _02_DuplicateEmailAddress()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02- Duplicate Email Address", ((string[])(null)));
#line 152
this.ScenarioSetup(scenarioInfo);
#line 153
 testRunner.Given("I navigate to the url \"\" titled \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 154
 testRunner.When("I click on the link containing the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 155
 testRunner.And("I set the text box using element id \"\" with the value \"Ravi\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 156
 testRunner.And("I set the text box using element id \"\" with the value \"Radha-EmailAddr\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 157
 testRunner.And("I set the text box using element id \"\" with the value \"ravi.radhakrishnan@variq.c" +
                    "om\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 158
 testRunner.And("I set the text box using element id \"\" with the value \"mypasswd$0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
 testRunner.And("I set the text box using element id \"\" with the value \"2600 Tower Oaks Blvd\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 160
 testRunner.And("I set the text box using element id \"\" with the value \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 161
 testRunner.And("I set the text box using element id \"\" with the value \"Maryland\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
 testRunner.And("I set the text box using element id \"\" with the value \"20876\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 163
 testRunner.And("I set the text box using element id \"\" with the value \"5466809223001601\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 164
 testRunner.And("I set the text box using element id \"\" with the value \"12\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 165
 testRunner.And("I set the text box using element id \"\" with the value \"19\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 166
 testRunner.And("I set the text box using element id \"\" with the value \"216\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 167
 testRunner.And("I select the drop down text \"*** Any Security Question ****\" using element id \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 168
 testRunner.And("I click on the button using element id \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 169
 testRunner.Then("the page title is \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 170
 testRunner.And("the page contains the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 171
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03-Register new user with User ID")]
        public virtual void _03_RegisterNewUserWithUserID()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03-Register new user with User ID", ((string[])(null)));
#line 173
this.ScenarioSetup(scenarioInfo);
#line 174
 testRunner.Given("I navigate to the url \"\" titled \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 175
 testRunner.When("I click on the link containing the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 176
 testRunner.And("I set the text box using element id \"\" with the value \"Ravi\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 177
 testRunner.And("I set the text box using element id \"\" with the value \"Radha-UserID\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 178
 testRunner.And("I set the text box using element id \"\" with the value \"ravi.radhakrishnan\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 179
 testRunner.And("I set the text box using element id \"\" with the value \"mypasswd$0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 180
 testRunner.And("I set the text box using element id \"\" with the value \"2600 Tower Oaks Blvd\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 181
 testRunner.And("I set the text box using element id \"\" with the value \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 182
 testRunner.And("I set the text box using element id \"\" with the value \"Maryland\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 183
 testRunner.And("I set the text box using element id \"\" with the value \"20876\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 184
 testRunner.And("I set the text box using element id \"\" with the value \"5466809223001601\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 185
 testRunner.And("I set the text box using element id \"\" with the value \"12\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 186
 testRunner.And("I set the text box using element id \"\" with the value \"19\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 187
 testRunner.And("I set the text box using element id \"\" with the value \"216\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 188
 testRunner.And("I select the drop down text \"*** Any Security Question ****\" using element id \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 189
 testRunner.And("I click on the button using element id \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 190
 testRunner.Then("the page title is \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 191
 testRunner.And("I click on the link containing the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04- Duplicate User ID")]
        public virtual void _04_DuplicateUserID()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04- Duplicate User ID", ((string[])(null)));
#line 193
this.ScenarioSetup(scenarioInfo);
#line 194
 testRunner.Given("I navigate to the url \"\" titled \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 195
 testRunner.When("I click on the link containing the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 196
 testRunner.And("I set the text box using element id \"\" with the value \"Ravi\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 197
 testRunner.And("I set the text box using element id \"\" with the value \"Radha-UserId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 198
 testRunner.And("I set the text box using element id \"\" with the value \"ravi.radhakrishnan\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 199
 testRunner.And("I set the text box using element id \"\" with the value \"mypasswd$0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 200
 testRunner.And("I set the text box using element id \"\" with the value \"2600 Tower Oaks Blvd\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 201
 testRunner.And("I set the text box using element id \"\" with the value \"Rockville\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 202
 testRunner.And("I set the text box using element id \"\" with the value \"Maryland\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 203
 testRunner.And("I set the text box using element id \"\" with the value \"20876\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 204
 testRunner.And("I set the text box using element id \"\" with the value \"5466809223001601\" # CC Num" +
                    "ber", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 205
 testRunner.And("I set the text box using element id \"\" with the value \"12\"  # CC Exp Month", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 206
 testRunner.And("I set the text box using element id \"\" with the value \"19\"  # CC Exp Year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 207
 testRunner.And("I set the text box using element id \"\" with the value \"216\" # CC Sec Code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 208
 testRunner.And("I select the drop down text \"*** Any Security Question ****\" using element id \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 209
 testRunner.And("I click on the button using element id \"\"  # Register Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 210
 testRunner.Then("the page title is \"\"  # Duplicate Email Address error page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 211
 testRunner.And("the page contains the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 212
 testRunner.And("I close the current page  # Close browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10- Verify Product Catalog page - Item Name & Price")]
        [NUnit.Framework.TestCaseAttribute("1", "Item 1", new string[0])]
        [NUnit.Framework.TestCaseAttribute("1", "60.00", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2", "Item 2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2", "70", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "Item 3", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "80", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4", "Item 4", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4", "90", new string[0])]
        [NUnit.Framework.TestCaseAttribute("5", "Item 5", new string[0])]
        [NUnit.Framework.TestCaseAttribute("5", "100", new string[0])]
        public virtual void _10_VerifyProductCatalogPage_ItemNamePrice(string tableRowNumber, string data, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10- Verify Product Catalog page - Item Name & Price", exampleTags);
#line 214
this.ScenarioSetup(scenarioInfo);
#line 215
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 216
 testRunner.When("I access the table using element id \"\"  # Product Catalog table", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 217
 testRunner.Then(string.Format("table row number {0} contains the values {1} from the following table", tableRowNumber, data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11- Product Catalog - Select items and click on Shopping Cart")]
        public virtual void _11_ProductCatalog_SelectItemsAndClickOnShoppingCart()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11- Product Catalog - Select items and click on Shopping Cart", ((string[])(null)));
#line 232
this.ScenarioSetup(scenarioInfo);
#line 233
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 235
 testRunner.And("I click on the button using element id \"\"  # Shopping Cart Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 236
 testRunner.Then("the page title is \"\"  # Shopping Cart page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("12-Verify Shopping Cart")]
        [NUnit.Framework.TestCaseAttribute("1", "Item 1", new string[0])]
        [NUnit.Framework.TestCaseAttribute("1", "1", new string[0])]
        [NUnit.Framework.TestCaseAttribute("1", "60.00", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2", "Item 2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2", "2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2", "70", new string[0])]
        public virtual void _12_VerifyShoppingCart(string tableRowNumber, string data, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12-Verify Shopping Cart", exampleTags);
#line 238
this.ScenarioSetup(scenarioInfo);
#line 239
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 240
 testRunner.When("I access the table using element id \"\"  # Shopping Cart table", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 241
 testRunner.Then("the text box using element id \"\" contains the value \"\"  # Total Cost", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 242
 testRunner.Then(string.Format("table row number {0} contains the values {1} from the following table", tableRowNumber, data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("13-From Shopping Cart go to Product Catalog Page")]
        public virtual void _13_FromShoppingCartGoToProductCatalogPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13-From Shopping Cart go to Product Catalog Page", ((string[])(null)));
#line 253
this.ScenarioSetup(scenarioInfo);
#line 254
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 255
 testRunner.When("I click on the button using element id \"\"  # Return to Product Catalog", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 256
 testRunner.And("the page title is \"\"  # Product Catalog page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 258
 testRunner.And("I click on the button using element id \"\"  # Shopping Cart Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 259
 testRunner.Then("the page title is \"\"  # Shopping Cart page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("14-Shopping Cart Page - Verify final details of product selections")]
        [NUnit.Framework.TestCaseAttribute("1", "Item 1", new string[0])]
        [NUnit.Framework.TestCaseAttribute("1", "1", new string[0])]
        [NUnit.Framework.TestCaseAttribute("1", "60.00", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2", "Item 2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2", "2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2", "70", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "Item 3", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "3", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "90", new string[0])]
        public virtual void _14_ShoppingCartPage_VerifyFinalDetailsOfProductSelections(string tableRowNumber, string data, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14-Shopping Cart Page - Verify final details of product selections", exampleTags);
#line 261
this.ScenarioSetup(scenarioInfo);
#line 262
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 263
 testRunner.Then("the text box using element id \"\" contains the value \"\"  # Total Cost", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 264
 testRunner.And(string.Format("table row number {0} contains the values {1} from the following table", tableRowNumber, data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("15- Go to Checkout")]
        public virtual void _15_GoToCheckout()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("15- Go to Checkout", ((string[])(null)));
#line 278
this.ScenarioSetup(scenarioInfo);
#line 279
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 280
 testRunner.When("I click on the button using element id \"\"  # Review Order page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 281
 testRunner.Then("the page title is \"\"  # Review Order page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("16- Verify Review Order Page - Item Names, Count, Cost, CC, Shipping Address")]
        [NUnit.Framework.TestCaseAttribute("1", "Item 1", new string[0])]
        [NUnit.Framework.TestCaseAttribute("1", "1", new string[0])]
        [NUnit.Framework.TestCaseAttribute("1", "60.00", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2", "Item 2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2", "2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2", "70", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "Item 3", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "3", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", "90", new string[0])]
        public virtual void _16_VerifyReviewOrderPage_ItemNamesCountCostCCShippingAddress(string tableRowNumber, string data, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("16- Verify Review Order Page - Item Names, Count, Cost, CC, Shipping Address", exampleTags);
#line 283
this.ScenarioSetup(scenarioInfo);
#line 284
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 285
 testRunner.Then("the text box using element id \"\" contains the value \"\"  # Total Cost", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 286
 testRunner.Then("the text box using element id \"\" contains the value \"\"  # CC Info", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 287
 testRunner.Then("the text box using element id \"\" contains the value \"\"  # Mailing Address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 288
 testRunner.And(string.Format("table row number {0} contains the values {1} from the following table", tableRowNumber, data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("17- Click on Submit Order and verify Confirmation Page")]
        public virtual void _17_ClickOnSubmitOrderAndVerifyConfirmationPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("17- Click on Submit Order and verify Confirmation Page", ((string[])(null)));
#line 302
this.ScenarioSetup(scenarioInfo);
#line 303
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 304
 testRunner.When("I click on the button using element id \"\"  # Submit Order button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 305
 testRunner.Then("the page title is \"\"  # Confirmation Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 306
 testRunner.And("the page contains the text \"\"  # Confirmation message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
